{
 "title": "API Calls",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   { "name": "Cloud", "label": "Cloud", "query": { "query": "up" } },
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "up{cloud=~\"$Cloud\"}"
    }
   },
   {
    "name": "Environment",
    "label": "Environment",
    "query": {
     "query": "up{cloud=~\"$Cloud\", location=~\"$Location\"}"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}"
    }
   },
   {
    "name": "ActiveTenantName",
    "label": "Tenant",
    "query": {
     "query": "iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}"
    }
   },
   {
    "name": "ActiveMailboxName",
    "label": "Mailbox",
    "query": {
     "query": "iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}"
    }
   },
   {
    "name": "IwdRequest_H",
    "label": "IwdRequest_H",
    "query": "getMailboxes,getOAuth2Tokens,reportConnectionStatus,bulkReportConnectionStatus"
   },
   {
    "name": "IwdRequest_M",
    "label": "IwdRequest_M",
    "query": "submitWorkItem,reportEmailSendingStatus,queryOutboundQueue"
   },
   {
    "name": "UcsRequest",
    "label": "UcsRequest",
    "query": "connect,getInteractionWOAttachments,findInteractionsByExternalId,getDocument,updateInteraction,insertInteraction,identifyContact,addDocument,deleteInteraction,getIdentifier,getContactAttributes"
   },
   {
    "name": "ImapRequest",
    "label": "ImapRequest",
    "query": "connect,disconnect,openBox,closeBox,search,getPartData,deleteMessage,addFlags"
   },
   { "name": "SmtpRequest", "label": "SmtpRequest", "query": "connect,disconnect,sendMail" },
   {
    "name": "GraphRequest",
    "label": "GraphRequest",
    "query": "getUserMailFolders,getUserMailFoldersMessages,getUserMessagesAttachmentsInfo,getUserMessagesAttachments,deleteUserMessages,patchUserMessages,getUserMessages,postUserMessages,postUserMessagesCreateReply,postUserMessagesAttachments,postUserMessagesSend,getUserMailFoldersMessagesCount"
   },
   {
    "name": "GmailRequest",
    "label": "GmailRequest",
    "query": "labelsList,messagesList,messagesGet,messagesAttachmentsGet,messagesDelete,messagesModify,messagesSend"
   }
  ]
 },
 "panels": [
  {
   "title": "IWD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$IwdRequest_H\" request per Tenant rate, rpm",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "repeat": "IwdRequest_H",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_iwd_($IwdRequest_H)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_iwd_($IwdRequest_H)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m])) by (domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "\"$IwdRequest_H\" request processing time per Tenant, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "repeat": "IwdRequest_H",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase({__name__=~\"iwdEmail_iwd_($IwdRequest_H)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))/sum (increase({__name__=~\"iwdEmail_iwd_($IwdRequest_H)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain) (increase({__name__=~\"iwdEmail_iwd_($IwdRequest_H)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))/sum by (domain)(increase({__name__=~\"iwdEmail_iwd_($IwdRequest_H)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "\"$IwdRequest_M\" request per Tenant rate, rpm",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "repeat": "IwdRequest_M",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_iwd_($IwdRequest_M)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_iwd_($IwdRequest_M)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m])) by (domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "\"$IwdRequest_M\" request processing time per Tenant, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "repeat": "IwdRequest_M",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase({__name__=~\"iwdEmail_iwd_($IwdRequest_M)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))/sum (increase({__name__=~\"iwdEmail_iwd_($IwdRequest_M)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain) (increase({__name__=~\"iwdEmail_iwd_($IwdRequest_M)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))/sum by (domain)(increase({__name__=~\"iwdEmail_iwd_($IwdRequest_M)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UCS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$UcsRequest\" request per Tenant rate, rpm",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "repeat": "UcsRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_ucs_($UcsRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_ucs_($UcsRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m])) by (domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "\"$UcsRequest\" request processing time per Tenant, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "repeat": "UcsRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase({__name__=~\"iwdEmail_ucs_($UcsRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))/sum (increase({__name__=~\"iwdEmail_ucs_($UcsRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain) (increase({__name__=~\"iwdEmail_ucs_($UcsRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))/sum by (domain)(increase({__name__=~\"iwdEmail_ucs_($UcsRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IMAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$ImapRequest\" request rate, rpm",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "repeat": "ImapRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_imap_($ImapRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_imap_($ImapRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_imap_($ImapRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m])) by (domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "\"$ImapRequest\" request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "repeat": "ImapRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase({__name__=~\"iwdEmail_imap_($ImapRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))/sum (increase({__name__=~\"iwdEmail_imap_($ImapRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_imap_($ImapRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))/sum by (domain)(increase({__name__=~\"iwdEmail_imap_($ImapRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum by (domain,mailbox) (increase({__name__=~\"iwdEmail_imap_($ImapRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))/sum by (domain,mailbox)(increase({__name__=~\"iwdEmail_imap_($ImapRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  },
  {
   "title": "SMTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$SmtpRequest\" request rate, rpm",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "repeat": "SmtpRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m])) by (domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "\"$SmtpRequest\" request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "repeat": "SmtpRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))/sum (increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))/sum by (domain)(increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum by (domain,mailbox) (increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))/sum by (domain,mailbox)(increase({__name__=~\"iwdEmail_smtp_($SmtpRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  },
  {
   "title": "GRAPH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$GraphRequest\" request rate, rpm",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "repeat": "GraphRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_graph_($GraphRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_graph_($GraphRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_graph_($GraphRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m])) by (domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "\"$GraphRequest\" request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "repeat": "GraphRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase({__name__=~\"iwdEmail_graph_($GraphRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))/sum (increase({__name__=~\"iwdEmail_graph_($GraphRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_graph_($GraphRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))/sum by (domain)(increase({__name__=~\"iwdEmail_graph_($GraphRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum by (domain,mailbox) (increase({__name__=~\"iwdEmail_graph_($GraphRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))/sum by (domain,mailbox)(increase({__name__=~\"iwdEmail_graph_($GraphRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  },
  {
   "title": "GMAIL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$GmailRequest\" request rate, rpm",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "repeat": "GmailRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum(increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_total\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m])) by (domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "\"$GmailRequest\" request processing time, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "repeat": "GmailRequest",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))/sum (increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (domain)(increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))/sum by (domain)(increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
       "legendFormat": "Domain: {{domain}}"
      },
      {
       "expr": "sum by (domain,mailbox) (increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_duration_milliseconds_sum\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))/sum by (domain,mailbox)(increase({__name__=~\"iwdEmail_gmail_($GmailRequest)_duration_milliseconds_count\", cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  }
 ]
}