{
 "title": "iWD Email Connector",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Cloud", "label": "Cloud", "query": { "query": "up" } },
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "up{cloud=~\"$Cloud\"}"
    }
   },
   {
    "name": "Environment",
    "label": "Environment",
    "query": {
     "query": "up{cloud=~\"$Cloud\", location=~\"$Location\"}"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "iWDEmail nodejs heap size, MB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iwdEmail_nodejs_heap_size_used_bytes{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}/(1024*1024)",
     "legendFormat": "Used({{pod}})"
    },
    {
     "expr": "iwdEmail_nodejs_heap_size_total_bytes{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}/(1024*1024)",
     "legendFormat": "Total({{pod}})"
    }
   ]
  },
  {
   "title": "iWDEmail Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(iwdEmail_process_cpu_seconds_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}[1m])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "iWDEmail Active handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iwdEmail_nodejs_active_handles_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IWDEmail API Request per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(iwdEmail_api_request_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}[1m])",
     "legendFormat": "{{path}}({{pod}})"
    }
   ]
  },
  {
   "title": "iWDEmail Error per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(iwdEmail_errors_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "iWDEmail Request timeouts ( http 504 )  per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(iwdEmail_api_request_closed{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sleeping \"threads\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(iwdEmail_sleeping_threads{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "iwdEmail_sleeping_threads{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(max_over_time(iwdEmail_sleeping_threads{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[10m])) == bool 0",
     "legendFormat": "Scale Up"
    },
    {
     "expr": "sum(min_over_time(iwdEmail_sleeping_threads{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[10m])) > bool 5",
     "legendFormat": "Scale Down"
    }
   ]
  }
 ]
}