{
 "title": "Email Processing",
 "tags": [
  "__iwd__",
  "__iwdem__",
  "__digital__"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   { "name": "Cloud", "label": "Cloud", "query": { "query": "up" } },
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "up{cloud=~\"$Cloud\"}"
    }
   },
   {
    "name": "Environment",
    "label": "Environment",
    "query": {
     "query": "up{cloud=~\"$Cloud\", location=~\"$Location\"}"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}"
    }
   },
   {
    "name": "ActiveTenantName",
    "label": "Tenant",
    "query": {
     "query": "iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\"}"
    }
   },
   {
    "name": "ActiveMailboxName",
    "label": "Mailbox",
    "query": {
     "query": "iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}"
    }
   },
   {
    "name": "ActiveInboundProtocol",
    "label": "Inbound Protocol",
    "query": {
     "query": "iwdEmail_inbound_server_connection_status{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}"
    }
   },
   {
    "name": "ActiveOutboundProtocol",
    "label": "Outbound Protocol",
    "query": {
     "query": "iwdEmail_outbound_server_connection_status{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}"
    }
   },
   {
    "name": "InboundSubtype",
    "label": "InboundSubtype",
    "query": "InboundNew,InboundCustomerReply,Unknown"
   },
   {
    "name": "OutboundSubtype",
    "label": "OutboundSubtype",
    "query": "OutboundNew,OutboundReply,OutboundAcknowledgement,OutboundAutoResponse,OutboundRedirect,Unknown"
   }
  ]
 },
 "panels": [
  {
   "title": "iWD Connectivity Status per Tenant",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\niwdEmail_iwd_connection_status\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\"} \n) by (cloud,location,environment,domain) > bool 0",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "UCS Connectivity Status per Tenant",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(\niwdEmail_ucs_connection_status\n{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}\n) by (cloud,location,environment,domain) > bool 0",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Nexus Connectivity Status",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(\niwdEmail_nexus_connection_status\n{cloud=~\"$Cloud\", location=~\"$Location\", environment=~\"$Environment\", pod=~\"$Pod\"}\n) by (cloud,location,environment) > bool 0",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Redis Connectivity Status",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "(\ncount(\niwdEmail_redis_connections_ready\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}\n) - sum(\niwdEmail_redis_connections_ready\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\"}\n)\n) == bool 0",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Percentage of failed inbound mailboxes",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(\niwdEmail_inbound_server_connection_status\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}\n)  by (domain) /\ncount(\niwdEmail_inbound_server_connection_status\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}\n) by (domain)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Percentage of failed outbound mailboxes",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(\niwdEmail_inbound_server_connection_status\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}\n)  by (domain) /\ncount(\niwdEmail_inbound_server_connection_status\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}\n) by (domain)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "Mailbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Inbound Mailbox Connectivity Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\niwdEmail_inbound_server_connection_status\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}\n) by (cloud,location,environment,domain,mailbox) > bool 0",
     "legendFormat": "{{mailbox}}({{domain}})"
    }
   ]
  },
  {
   "title": "Outbound Mailbox Connectivity Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(\niwdEmail_outbound_server_connection_status\n{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}\n) by (cloud,location,environment,domain,mailbox) > bool 0",
     "legendFormat": "{{mailbox}}({{domain}})"
    }
   ]
  },
  {
   "title": "Mailbox processing average time per Tenant, sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0.001 * \nsum by (cloud,location,environment,domain) (rate(iwdEmail_mailbox_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m])) / \nsum by (cloud,location,environment,domain)\n(rate(iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\"}[1m]))",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Mailbox processing average time, sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0.001 * \nsum by (cloud,location,environment,domain,mailbox) (rate(iwdEmail_mailbox_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m])) / \nsum by (cloud,location,environment,domain,mailbox)\n(rate(iwdEmail_mailbox_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\"}[1m]))",
     "legendFormat": "{{mailbox}}({{domain}})"
    }
   ]
  },
  {
   "title": "Inbound Emails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Emails per Tenant rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_processed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_processed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Inbound Emails per Mailbox rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_processed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\", subtype=~\"$InboundSubtype\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Inbound Email processing average time per Tenant, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(iwdEmail_inbound_email_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))/sum (rate(iwdEmail_inbound_email_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "sum by (cloud,location,environment,domain) (rate(iwdEmail_inbound_email_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain)(rate(iwdEmail_inbound_email_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Inbound Email processing average time per Mailbox, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cloud,location,environment,domain,mailbox) (rate(iwdEmail_inbound_email_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain,mailbox)(rate(iwdEmail_inbound_email_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Inbound Emails Size per Tenant rate, KB/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_size_kb_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_size_kb_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Inbound Emails Size per Mailbox rate, KB/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_size_kb_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Inbound Queue size per Tenant, emails",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(iwdEmail_inbound_unread_emails_in_mailbox{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(iwdEmail_inbound_unread_emails_in_mailbox{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Inbound Queue size per Mailbox, emails",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(iwdEmail_inbound_unread_emails_in_mailbox{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Average waiting time in Inbound Queue per Tenant, sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(iwdEmail_inbound_email_waiting_time_seconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))/sum (rate(iwdEmail_inbound_email_waiting_time_seconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "sum by (cloud,location,environment,domain) (rate(iwdEmail_inbound_email_waiting_time_seconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain)(rate(iwdEmail_inbound_email_waiting_time_seconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Average waiting time in Inbound Queue per Mailbox, sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cloud,location,environment,domain,mailbox) (rate(iwdEmail_inbound_email_waiting_time_seconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain,mailbox)(rate(iwdEmail_inbound_email_waiting_time_seconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Inbound Email Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Email Failures per Tenant rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_failed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_failed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Inbound Email Failures per Mailbox rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_failed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\", subtype=~\"$InboundSubtype\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Inbound Email Retries per Tenant rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_to_retry_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_to_retry_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Inbound Email Retries per Mailbox rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_to_retry_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\", subtype=~\"$InboundSubtype\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Rejected by content Inbound Emails per Tenant rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_blocked_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_blocked_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Rejected by content Inbound Emails per Mailbox rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_blocked_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Rejected Inbound Email Attachments per Tenant rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_blocked_attachments_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_blocked_attachments_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Rejected Inbound Email Attachments per Mailbox rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_inbound_emails_blocked_attachments_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Emails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound Emails per Tenant, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_sent_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_sent_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Outbound Emails per Mailbox, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_sent_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\", subtype=~\"$OutboundSubtype\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Outbound Email processing average time per Tenant, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(iwdEmail_outbound_email_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))/sum (rate(iwdEmail_outbound_email_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "sum by (cloud,location,environment,domain) (rate(iwdEmail_outbound_email_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain)(rate(iwdEmail_outbound_email_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Outbound Email processing average time per Mailbox, ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cloud,location,environment,domain,mailbox) (rate(iwdEmail_outbound_email_processing_duration_milliseconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain,mailbox)(rate(iwdEmail_outbound_email_processing_duration_milliseconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Outbound Emails Size per Tenant, KB/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_size_kb_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_size_kb_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Outbound Emails Size per Mailbox, KB/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_size_kb_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Outbound Queue size per Tenant, emails",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(iwdEmail_outbound_emails_in_queue{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(iwdEmail_outbound_emails_in_queue{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Outbound Queue size per Mailbox, emails",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(iwdEmail_outbound_emails_in_queue{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\"}) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Average waiting time in Outbound Queue per Tenant, sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(iwdEmail_outbound_email_waiting_time_seconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))/sum (rate(iwdEmail_outbound_email_waiting_time_seconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "sum by (cloud,location,environment,domain) (rate(iwdEmail_outbound_email_waiting_time_seconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain)(rate(iwdEmail_outbound_email_waiting_time_seconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Average waiting time in Outbound Queue per Mailbox, sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cloud,location,environment,domain,mailbox) (rate(iwdEmail_outbound_email_waiting_time_seconds_sum{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))/sum by (cloud,location,environment,domain,mailbox)(rate(iwdEmail_outbound_email_waiting_time_seconds_count{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\"}[1m]))",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Email Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound Email Failures per Tenant rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_failed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_failed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Outbound Email Failures per Mailbox rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_failed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\", subtype=~\"$OutboundSubtype\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    },
    {
     "title": "Outbound Email Retries per Tenant rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_to_retry_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_to_retry_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", protocol=~\"$ActiveOutboundProtocol\"}[1m])) by (cloud,location,environment,domain)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Outbound Email Retries per Mailbox rate, email/min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(iwdEmail_outbound_emails_to_retry_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\", subtype=~\"$OutboundSubtype\"}[1m])) by (cloud,location,environment,domain,mailbox)",
       "legendFormat": "{{mailbox}}({{domain}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queried Inbound Emails of Total, %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 * sum (increase(iwdEmail_inbound_emails_processed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveInboundProtocol\", subtype=~\"$InboundSubtype\"}[1m]))/(1e-30+sum (increase (iwdEmail_inbound_emails_processed_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m])))",
       "legendFormat": "Pod:$Pod,  Tenant:$ActiveTenantName, Mailbox:$ActiveMailboxName, Protocol:$ActiveInboundProtocol"
      }
     ]
    },
    {
     "title": "Queried Outbound Emails of Total, %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 * sum (increase(iwdEmail_outbound_emails_sent_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\",pod=~\"$Pod\", domain=~\"$ActiveTenantName\", mailbox=~\"$ActiveMailboxName\", protocol=~\"$ActiveOutboundProtocol\", subtype=~\"$OutboundSubtype\"}[1m]))/(1e-30+sum (increase (iwdEmail_outbound_emails_sent_total{cloud=~\"$Cloud\",location=~\"$Location\",environment=~\"$Environment\"}[1m])))",
       "legendFormat": "Pod:$Pod,  Tenant:$ActiveTenantName, Mailbox:$ActiveMailboxName, Protocol:$ActiveInboundProtocol"
      }
     ]
    }
   ]
  }
 ]
}