{
 "title": "WebRTC Service Dashboard",
 "tags": [ "webrtc" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Region", "label": "Prometheus Region", "query": "prometheus" },
   { "name": "Color", "label": "Displayed Deployment Color:", "query": "blue, green" },
   {
    "name": "GWINSTANCES",
    "label": "Gateway EC2 Instances",
    "query": "up{namespace=\"WEBRTC\", instance_name=~\"(?i)webrtc-gateway-$Color\"}"
   },
   {
    "name": "COTURNINSTANCES",
    "label": "Coturn ECS2 Instances",
    "query": "up{instance_service=\"WEBRTC\", instance_name=~\"(?i)$StackName-coturn-$Color-EC2-instance\", aws_cloudformation_stack_name=\"$StackName\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Active color",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_ingress_labels{namespace=\"webrtc\",ingress=\"webrtc-ingress-int\", label_active=\"blue\"}",
     "legendFormat": "{{label_active}} ({{label_helm_sh_chart}}"
    },
    {
     "expr": "kube_ingress_labels{namespace=\"webrtc\",ingress=\"webrtc-ingress-int\", label_active=\"green\"}",
     "legendFormat": "{{label_active}} ({{label_helm_sh_chart}}"
    }
   ]
  },
  {
   "title": "VERSIONS",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_labels{deployment=\"webrtc-gateway-blue\"}",
     "legendFormat": "BLU: {{label_app_kubernetes_io_version}}"
    },
    {
     "expr": "kube_deployment_labels{deployment=\"webrtc-gateway-blue\"}",
     "legendFormat": "BLU: {{label_helm_sh_chart}}"
    },
    {
     "expr": "kube_deployment_labels{deployment=\"webrtc-gateway-green\"}",
     "legendFormat": "GRE: {{label_app_kubernetes_io_version}}"
    },
    {
     "expr": "kube_deployment_labels{deployment=\"webrtc-gateway-green\"}",
     "legendFormat": "GRE: {{label_helm_sh_chart}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( kube_pod_container_status_ready{namespace=\"webrtc\", pod=~\"webrtc-coturn-green.*\" } )",
     "legendFormat": "Coturn Green"
    },
    {
     "expr": "sum( kube_pod_container_status_ready{namespace=\"webrtc\", pod=~\"webrtc-coturn-blue.*\" } )",
     "legendFormat": "Coturn Blue"
    },
    {
     "application": { "filter": "" },
     "expr": "count(wrtc_current_signins{color=\"blue\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Gateway Blue",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "count(wrtc_current_signins{color=\"green\"})",
     "legendFormat": "Gateway Green"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "count( wrtc_current_signins{ color=\"$Color\" } )",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Coturns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum( kube_pod_container_status_ready{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\" } )",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Auth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-floor(avg(wrtc_system_error{type=\"auth\", color=\"$Color\"}))"
    }
   ]
  },
  {
   "title": "Env",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-floor(avg(wrtc_system_error{type=\"env\", color=\"$Color\"}))"
    }
   ]
  },
  {
   "title": "Gateway CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg(machine_cpu_cores)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Cores",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cfg",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-floor(avg(wrtc_system_error{type=\"cfg\", color=\"$Color\"}))"
    }
   ]
  },
  {
   "title": "ES",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-floor(avg(wrtc_system_error{type=\"es\", color=\"$Color\"}))"
    }
   ]
  },
  {
   "title": "Current Number of Registered DNs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_current_signins{ color=\"$Color\" })",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Registrations $Color",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_registrations_by_domain{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "All",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "sum(wrtc_registrations_by_domain{color=\"$Color\"}) by (domain)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Registrations Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kube_hpa_spec_target_metric{namespace=\"webrtc\", hpa=\"keda-hpa-webrtc-gateway-scobj-$Color\", metric_name=~\".*signins\"}",
     "legendFormat": "Scale Limit"
    },
    {
     "expr": "100.0*avg( wrtc_current_signins{ color=\"$Color\" } ) / min(wrtc_max_clients_per_instance{ color=\"$Color\" } )",
     "legendFormat": "Occupied"
    }
   ]
  },
  {
   "title": "Current Number of Calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_current_audio_calls{ color=\"$Color\" })",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Peak Number of Calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_peak_audio_calls{ color=\"$Color\" })",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Number of Calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_total_audio_calls{ color=\"$Color\" })",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Current Number of Transcoded Calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_current_xcoding_calls{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Peak Number of transcoded Calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_peak_xcoding_calls{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total transoding Calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_total_xcoding_calls{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Current audio calls on $Color",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_current_audio_calls{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Audio Calls on $Color",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_total_audio_calls{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Calls transcoding calls on $Color",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_current_xcoding_calls{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Transcoding Calls on $Color",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_total_xcoding_calls{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Auth Connection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-avg(wrtc_system_error{type=\"auth\", color=\"$Color\"})"
    }
   ]
  },
  {
   "title": "Env Connection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-avg(wrtc_system_error{type=\"env\", color=\"$Color\"})"
    }
   ]
  },
  {
   "title": "Cfg Connection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-avg(wrtc_system_error{type=\"cfg\", color=\"$Color\"})"
    }
   ]
  },
  {
   "title": "ElasticSearch connection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-avg(wrtc_system_error{type=\"es\", color=\"$Color\"})"
    }
   ]
  },
  {
   "title": "CPU Usage - Gateway",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_cpu_cores{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\"} * 1000) ",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\", container=\"webrtc\"}[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage - Coturn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_cpu_cores{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\"} * 1000) ",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\", container=\"coturn\"}[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Gateway",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_memory_bytes{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\"} ) ",
     "legendFormat": "Memory Requested"
    },
    {
     "expr": "(container_memory_working_set_bytes{namespace=\"webrtc\", pod=~\"webrtc-gateway-$Color.*\", container=\"webrtc\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Coturn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests_memory_bytes{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\"} ) ",
     "legendFormat": "Memory Requested"
    },
    {
     "expr": "(container_memory_working_set_bytes{namespace=\"webrtc\", pod=~\"webrtc-coturn-$Color.*\", container=\"coturn\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RTP Packets errors on $Color",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "delta(sum(wrtc_rtp_losts{color=\"$Color\"})[5m:])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "lost",
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "delta(sum(wrtc_rtp_errors{color=\"$Color\"})[5m:])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "WWE Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (idelta( wwe_ui_events{eventName=~\"error_webrtc.*\", eventName!~\".*enable_media_failed\", eventName!~\".*failed_browser_unsupported\"}[$__interval]  ))by (eventName, tenantName)",
     "legendFormat": "{{tenantName}} - {{eventName}}"
    }
   ]
  },
  {
   "title": "RTP Lost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 52 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_losts{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {}
   ]
  },
  {
   "title": "RTP Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 52 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_errors{color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {}
   ]
  },
  {
   "title": "GW Jitter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "delta(sum(wrtc_rtp_gateway_jitter{over=\"100\",color=\"$Color\"})[5m:])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "100",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "delta(sum(wrtc_rtp_gateway_jitter{over=\"300\",color=\"$Color\"})[5m:])",
     "legendFormat": "300"
    },
    {
     "expr": "delta(sum(wrtc_rtp_gateway_jitter{over=\"500\",color=\"$Color\"})[5m:])",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Client Jitter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "delta(sum(wrtc_rtp_client_jitter{over=\"100\",color=\"$Color\"})[5m:])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "100",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "delta(sum(wrtc_rtp_client_jitter{over=\"300\",color=\"$Color\"})[5m:])",
     "legendFormat": "300"
    },
    {
     "expr": "delta(sum(wrtc_rtp_client_jitter{over=\"500\",color=\"$Color\"})[5m:])",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "GW Jitter > 100",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 61 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_gateway_jitter{over = \"100\", color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GW Jitter > 300",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 61 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_gateway_jitter{over = \"300\", color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GW Jitter > 500",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 61 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_gateway_jitter{over = \"500\", color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Client Jitter > 100",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 61 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_client_jitter{over = \"100\", color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Client Jitter > 300",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 61 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_client_jitter{over = \"300\", color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Client Jitter > 500",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 61 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wrtc_rtp_client_jitter{over = \"500\", color=\"$Color\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}