{
 "title": "GWS ERRORS",
 "tags": [ "gws" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "code",
    "query": "gws_responses_total{namespace=\"{{ $.Release.Namespace }}\"}"
   },
   {
    "name": "service",
    "query": "gws_responses_total{namespace=\"{{ $.Release.Namespace }}\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "WORKSPACE API Errors by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (category, statusCode) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"incoming\", statusCode=~\"$code\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`}}`}} - {{`{{`}}statusCode{{`}}`}}"
    }
   ]
  },
  {
   "title": "WORKSPACE PLATFORM Errors by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (category, statusCode) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"outgoing\", statusCode=~\"$code\",namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`}}`}} - {{`{{`}}statusCode{{`}}`}}"
    }
   ]
  },
  {
   "title": "JAVA API errors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(service,code)(rate(gws_responses_total{code=~\"$code\",service=~\"$service\",namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}} - {{`{{`}}code{{`}}`}}"
    }
   ]
  },
  {
   "title": "JAVA API requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(api_requests_seconds_count_total{service=~\"$service\",namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "JAVA PSDK connection errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(delta(psdk_conn_error_total{service=~\"$service\",namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  },
  {
   "title": "JAVA API requests latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(api_requests_seconds_sum_total{service=~\"$service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])) / sum by(service)(rate(api_requests_seconds_count_total{service=~\"$service\",namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}service{{`}}`}}"
    }
   ]
  }
 ]
}