{
 "title": "GWS Platform instance",
 "tags": [ "gws" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Instance",
    "query": "jvm_memory_used_bytes{namespace=\"{{ $.Release.Namespace }}\"}"
   },
   {
    "name": "Service",
    "query": "query_result(jvm_memory_used_bytes{namespace=\"{{ $.Release.Namespace }}\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "API requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_seconds_count_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "API requests latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_seconds_sum_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m]) / rate(api_requests_seconds_count_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Active contexts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gws_context_active{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Active subscripitons",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, job)(gws_sub_active{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "PSDK events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, job)(rate(psdk_event_total{instance=~\"$Instance\", service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "PSDK connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(psdk_conn_opened_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "open {{`{{`}}instance{{`}}`}}"
    },
    {
     "expr": "delta(psdk_conn_error_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "error {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Subscriptions by env (top10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(environment)(gws_sub_active{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}))",
     "legendFormat": "{{`{{`}}environment{{`}}`}}"
    }
   ]
  },
  {
   "title": "PSDK events by env (top10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(environment)(rate(psdk_event_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])))",
     "legendFormat": "{{`{{`}}environment{{`}}`}}"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=\"{{ $.Release.Namespace }}\", instance=~\"$Instance\", service=~\"$Service\"}",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance,job)(jvm_memory_used_bytes{namespace=\"{{ $.Release.Namespace }}\", instance=~\"$Instance\", service=~\"$Service\"})",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "GC pause",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, job)(rate(jvm_gc_pause_seconds_sum{namespace=\"{{ $.Release.Namespace }}\", instance=~\"$Instance\", service=~\"$Service\"}[5m]))",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, job)(rate(jvm_gc_pause_seconds_count{namespace=\"{{ $.Release.Namespace }}\", instance=~\"$Instance\", service=~\"$Service\"}[5m]))",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Live threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"{{ $.Release.Namespace }}\", instance=~\"$Instance\", service=~\"$Service\"}",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Blocked threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{namespace=\"{{ $.Release.Namespace }}\", state=\"blocked\", instance=~\"$Instance\", service=~\"$Service\"}",
     "legendFormat": "{{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(request_out_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "{{`{{`}}instance{{`}}`}} to {{`{{`}}service{{`}}`}} status {{`{{`}}statusCode{{`}}`}}"
    }
   ]
  },
  {
   "title": "Subscriptions by transport",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(msgbus_sub_active{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "redis subs on {{`{{`}}instance{{`}}`}}"
    },
    {
     "expr": "sum by(instance)(comet_sub_active{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "comet on {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Contexts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(gws_context_opened_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "open {{`{{`}}instance{{`}}`}}"
    },
    {
     "expr": "delta(gws_context_error_total{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "error {{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Hikari pool stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}",
     "legendFormat": "active {{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    },
    {
     "expr": "delta(hikaricp_connections_usage_seconds_sum{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m]) / delta(hikaricp_connections_usage_seconds_count{instance=~\"$Instance\",service=~\"$Service\",namespace=\"{{ $.Release.Namespace }}\"}[5m])",
     "legendFormat": "avg {{`{{`}}job{{`}}`}} on {{`{{`}}instance{{`}}`}}"
    }
   ]
  }
 ]
}