{
 "title": "GWS Workspace",
 "tags": [ "gws" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Tenant", "query": "gws_app_workspace_tenants" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# User Activity" },
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gws_app_workspace_server_activity{metricName=\"cometd_active_user_count\", namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Users by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gws_app_workspace_server_activity{metricName=\"context_count\", namespace=\"{{ $.Release.Namespace }}\"}",
     "legendFormat": "{{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Users By Tenant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenantName) (gws_app_workspace_tenants{metricName=\"active_users\", namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "{{`{{`}}tenantName{{`}}`}}"
    }
   ]
  },
  {
   "title": "Users Pending Cleanup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gws_app_workspace_tenants{metricName=\"pending_cleanup\", namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "users pending cleanup"
    }
   ]
  },
  {
   "title": "Platform Logout Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gws_app_workspace_tenants{metricName=\"platform_logouts\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Platform Cometd Disconnect Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gws_app_workspace_tenants{metricName=\"platform_cometd_disconnects\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "disconnects"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 }, "content": "# Resource Usage" },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "cpu usage %" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{container=~\"gws-app-workspace.*\", namespace=\"{{ $.Release.Namespace }}\"}[1m])) * 100",
     "legendFormat": "{{`{{`}}name{{`}}`}}"
    }
   ]
  },
  {
   "title": "Node Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=\"{{ $.Release.Namespace }}\"}",
     "legendFormat": "{{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Node Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=\"{{ $.Release.Namespace }}\"}",
     "legendFormat": "{{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 }, "content": "# Requests" },
  {
   "title": "Incoming Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "req / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gws_app_workspace_requests{metricName=\"count\", type=\"incoming\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "req / sec"
    }
   ]
  },
  {
   "title": "Outgoing Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "req / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gws_app_workspace_requests{metricName=\"count\", type=\"outgoing\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "req / sec"
    }
   ]
  },
  {
   "title": "Incoming Request Rate by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "req / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (category) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"incoming\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing Request Rate by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "req / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (category) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"outgoing\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`{{`}}"
    }
   ]
  },
  {
   "title": "Incoming Request Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "req / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"incoming\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing Request Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "req / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"outgoing\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}instance{{`}}`}}"
    }
   ]
  },
  {
   "title": "API Error Response Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "errors / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (statusCode) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"incoming\", statusCode!~\"200|302\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}statusCode{{`}}`}}"
    }
   ]
  },
  {
   "title": "Platform Error Response Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "errors / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (statusCode) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"outgoing\", statusCode!~\"200|302\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}statusCode{{`}}`}}"
    }
   ]
  },
  {
   "title": "API Error Response Rates by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "errors / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (category, statusCode) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"incoming\", statusCode!~\"200|302\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`}}`}} - {{`{{`}}statusCode{{`}}`}}"
    }
   ]
  },
  {
   "title": "Platform Error Response Rates by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "errors / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (category, statusCode) (rate(gws_app_workspace_requests{metricName=\"count\", type=\"outgoing\", statusCode!~\"200|302\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`}}`}} - {{`{{`}}statusCode{{`}}`}}"
    }
   ]
  },
  {
   "title": "Average API Request Duration by Category",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "avg(gws_app_workspace_requests{metricName=\"avg_duration\", type=\"incoming\", category!='cometd', tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}) by (category)",
     "legendFormat": "{{`{{`}}category{{`}}`}}"
    }
   ]
  },
  {
   "title": "Average Platform Request Duration by Category",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "avg(gws_app_workspace_requests{metricName=\"avg_duration\", type=\"outgoing\", category!='cometd', tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}) by (category)",
     "legendFormat": "{{`{{`}}category{{`}}`}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 91 }, "content": "# Events" },
  {
   "title": "API Event Publication Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gws_app_workspace_events{metricName=\"count\", type=\"outgoing\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "events / sec"
    }
   ]
  },
  {
   "title": "Incoming Platform Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gws_app_workspace_events{metricName=\"count\", type=\"incoming\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "events / sec"
    }
   ]
  },
  {
   "title": "API Event Publication Rates by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (category) (rate(gws_app_workspace_events{metricName=\"count\", type=\"outgoing\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`}}`}}"
    }
   ]
  },
  {
   "title": "Incoming Platform Event Rates by Category",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (category) (rate(gws_app_workspace_events{metricName=\"count\", type=\"incoming\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}category{{`}}`}}"
    }
   ]
  },
  {
   "title": "API Event Publication Rates by Event Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short", "label": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (eventName) (rate(gws_app_workspace_events{metricName=\"count\", type=\"outgoing\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}eventName{{`}}`}}"
    }
   ]
  },
  {
   "title": "Incoming Platform Event Rates by Event Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short", "label": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (eventName) (rate(gws_app_workspace_events{metricName=\"count\", type=\"incoming\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}eventName{{`}}`}}"
    }
   ]
  },
  {
   "title": "Voice EventError Rates by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short", "label": "errors / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (eventDetail) (rate(gws_app_workspace_events{metricName=\"count\", type=\"incoming\", eventName=\"EventError\", category=\"voice\", eventDetail!=\"\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "Error {{`{{`}}eventDetail{{`}}`}}"
    }
   ]
  },
  {
   "title": "Non-Voice EventError Rates by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short", "label": "errors / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (eventDetail) (rate(gws_app_workspace_events{metricName=\"count\", type=\"incoming\", eventName=\"EventError\", category!=\"voice\", eventDetail!=\"\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}eventDetail{{`}}`}}"
    }
   ]
  },
  {
   "title": "CallStateChanged Rates by Notification Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short", "label": "events / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (eventName, eventDetail) (rate(gws_app_workspace_events{metricName=\"count\", type=\"outgoing\", category=\"voice\", eventName=\"CallStateChanged\", eventDetail!=\"\", tenantName=~\"$Tenant\", namespace=\"{{ $.Release.Namespace }}\"}[1m]))",
     "legendFormat": "{{`{{`}}eventName{{`}}`}} - {{`{{`}}eventDetail{{`}}`}}"
    }
   ]
  }
 ]
}