{
 "title": "Voice / Service / Tenant metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "tenant",
    "label": "tenant_id",
    "query": "label_values(tenant_tserver_health_level{tenant=~\".+\"},tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tenant Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tenant DN states",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(registrar_unregister_count{tenant=~\".+[[tenant]]$\"}[5m])) by (tenant)",
       "legendFormat": "OutOfService:{{tenant}}"
      },
      {
       "expr": "sum(increase(registrar_register_count{tenant=~\".+[[tenant]]$\"}[5m])) by (tenant)",
       "legendFormat": "InService:{{tenant}}"
      }
     ]
    },
    {
     "title": "Logged In Agents",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(agent_logged_in_agents{tenant=~\".+[[tenant]]$\"}) by (tenant)",
       "legendFormat": "{{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenant Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tenant's concurrent calls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tenant_tserver_active_calls{tenant=~\".+[[tenant]]$\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Call rate (call/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventCallCreated\"}[5m])) by (event, tenant)",
       "legendFormat": "{{ event }}:{{tenant}}"
      }
     ]
    },
    {
     "title": "Treatment applied (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventTreatmentApplied\"}[15m])) by (tenant) / sum(increase(sipnode_requests_total{tenant=~\".+[[tenant]]$\", request=\"RequestApplyTreatment\"}[15m])) by (tenant)",
       "legendFormat": "TreatmentApplied:{{ $sip_node }}:{{tenant}}"
      },
      {
       "expr": "sum(increase(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventTreatmentNotApplied\"}[15m])) by (tenant) / sum(increase(sipnode_requests_total{tenant=~\".+[[tenant]]$\", request=\"RequestApplyTreatment\"}[15m])) by (tenant)",
       "legendFormat": "TreatmentNotApplied:{{ $sip_node }}:{{tenant}}"
      }
     ]
    },
    {
     "title": "Call abandonment (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventAbandoned\"}[15m])) by (tenant) / sum(increase(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventCallCreated\"}[15m])) by (tenant)",
       "legendFormat": "{{ event }}:{{ $sip_node }}:{{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenant Call Routing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Default routed calls, last 5min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(sipnode_default_routing_total{tenant=~\"$tenant\"}[5m])) by (tenant)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "ORS metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (orsnode_interactions{tenant=~\".+[[tenant]]$\"}) by (tenant)",
       "legendFormat": "interactions:{{tenant}}"
      },
      {
       "expr": "sum (orsnode_strategies{tenant=~\".+[[tenant]]$\"}) by (tenant)",
       "legendFormat": "strategies:{{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenant Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "ORS Errors, last 5min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(orsnode_scxml_error_events{tenant=~\".+[[tenant]]$\"} [5m])) by(tenant, interaction_type)",
       "legendFormat": "scxml_error:{{interaction_type}}:{{tenant}}"
      },
      {
       "expr": "sum (increase(orsnode_load_errors{tenant=~\".+[[tenant]]$\"} [5m])) by(tenant, interaction_type)",
       "legendFormat": "load_errors:{{interaction_type}}:{{tenant}}"
      },
      {
       "expr": "sum (increase(orsnode_invoke_errors{tenant=~\".+[[tenant]]$\"} [5m])) by(tenant, interaction_type)",
       "legendFormat": "invoke_errors:{{interaction_type}}:{{tenant}}"
      },
      {
       "expr": "sum (increase(orsnode_urs_fetch_errors{tenant=~\".+[[tenant]]$\"} [5m])) by(tenant, interaction_type)",
       "legendFormat": "urs_fetch_errors:{{interaction_type}}:{{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIPFE: Tenant Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "tenant->sipfe (rq/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sipfe_requests_total{ tenant=~\".+[[tenant]]$\"}[1m])) by (tenant)",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "tenant<-sipfe (res/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sipfe_responses_total{ tenant=~\".+[[tenant]]$\"}[1m])) by (tenant, status)",
       "legendFormat": "{{status}}:{{ tenant }}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP Node: Tenant Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rates (rq/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sipnode_requests_total{tenant=~\".+[[tenant]]$\"}[5m])) by (tenant)",
       "legendFormat": "Total:{{tenant}}"
      },
      {
       "expr": "sum(irate(sipnode_requests_total{tenant=~\".+[[tenant]]$\", request=\"RequestApplyTreatment\"}[5m])) by (tenant)",
       "legendFormat": "Treatment:{{tenant}}"
      },
      {
       "expr": "sum(irate(sipnode_requests_total{tenant=~\".+[[tenant]]$\", request=\"RequestUpdateUserData\"}[5m])) by (tenant)",
       "legendFormat": "UserData:{{tenant}}"
      }
     ]
    },
    {
     "title": "Event rates (ev/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sipnode_events_total{tenant=~\".+[[tenant]]$\"}[5m])) by (tenant)",
       "legendFormat": "Total:{{tenant}}"
      },
      {
       "expr": "sum(irate(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventError\"}[5m])) by (tenant)",
       "legendFormat": "Error:{{tenant}}"
      },
      {
       "expr": "sum(irate(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventTreatmentApplied\"}[5m])) by (tenant)",
       "legendFormat": "TreatmentApplied:{{tenant}}"
      },
      {
       "expr": "sum(irate(sipnode_events_total{tenant=~\".+[[tenant]]$\", event=\"EventTreatmentNotApplied\"}[5m])) by (tenant)",
       "legendFormat": "TreatmentNotApplied:{{tenant}}"
      }
     ]
    }
   ]
  }
 ]
}