{
 "title": "Voice Kafka Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": "label_values({__name__=~\"kafka_(consumer|producer).*\", namespace=\"voice\"},pod)"
   },
   {
    "name": "container",
    "query": "label_values({__name__=~\"kafka_(consumer|producer).*\", namespace=\"voice\"},container)"
   },
   {
    "name": "topic",
    "query": "label_values({__name__=~\"(kafka_(consumer|producer).*)\", namespace=\"voice\"}, topic)"
   },
   {
    "name": "tenant",
    "query": "label_values({__name__=~\"kafka_(consumer|producer).*\", namespace=\"voice\"},tenant)"
   },
   {
    "name": "location",
    "query": "label_values({__name__=~\"kafka_(consumer|producer).*\", namespace=\"voice\"},location)"
   }
  ]
 },
 "panels": [
  {
   "title": "consumer errors rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_error_total{pod=~\"$pod\",container=~\"$container\",topic=~\"$topic\", location=~\".*$location.*\"}[5m])",
     "legendFormat": "error=\"{{error}}\", pod=\"{{pod}}\", container=\"{{container}}\", instance=\"{{instance}}\", topic=\"{{topic}}\", location=\"{{location}}\""
    }
   ]
  },
  {
   "title": "producer errors rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_error_total{pod=~\"$pod\",container=~\"$container\"}[5m])",
     "legendFormat": "error=\"{{error}}\", pod=\"{{pod}}\", container=\"{{container}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "consumer state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_state{container=~\"$container\", pod=~\"$pod\"}",
     "legendFormat": "pod=\"{{pod}}\", container=\"{{container}}\", instance=\"{{instance}}\", topic=\"{{topic}}\", location=\"{{location}}\""
    }
   ]
  },
  {
   "title": "producer state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_state{container=~\"$container\", pod=~\"$pod\"}",
     "legendFormat": "pod=\"{{pod}}\", container=\"{{container}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "consumer received messages rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_recv_messages_total{pod=~\"$pod\",container=~\"$container\",tenant=~\"$tenant\",topic=~\"$topic\"}[5m])",
     "legendFormat": "container=\"{{container}}\", pod=\"{{pod}}\", instance=\"{{instance}}\", topic=\"{{topic}}\", tenant=\"{{tenant}}\""
    }
   ]
  },
  {
   "title": "producer queue depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_queue_depth{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "pod=\"{{pod}}\", container=\"{{container}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "consumer rebalance rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_rebalance_total{pod=~\"$pod\",container=~\"$container\",topic=~\"$topic\",location=~\".*$location.*\"}[5m])",
     "legendFormat": "container=\"{{container}}\", pod=\"{{pod}}\", instance =\"{{instance}}\", topic=\"{{topic}}\", location=\"{{location}}\""
    }
   ]
  },
  {
   "title": "producer queue age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_queue_age_seconds{pod=~\"$pod\",container=~\"$container\",location=~\".*$location.*\"}",
     "legendFormat": " pod=\"{{pod}}\", container=\"{{container}}\", instance=\"{{instance}}\", location=\"{{location}}\""
    }
   ]
  },
  {
   "title": "consumer latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_consumer_latency_bucket{container=~\"$container\",topic=~\"$topic\",tenant=~\"$tenant\"}[5m])) by (le,container,tenant,topic))"
    }
   ]
  }
 ]
}