{
 "title": "Registrar Dashboard",
 "tags": [
  "voice",
  "registrar_node",
  "voice_common"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Registrar_redis_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registrar_redis_state{container=\"voice-registrar\"}",
     "legendFormat": "{{ pod }}-{{ redis_cluster_name }}"
    }
   ]
  },
  {
   "title": "log_output_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(rate(log_output_bytes_total{container=\"voice-registrar\",format=\"json\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\r(sum by(pod) (container_memory_working_set_bytes{pod=~\"voice-registrar.*\",image!=\"\",namespace=\"voice\"}) / sum by(pod)(kube_pod_container_resource_limits_memory_bytes{pod=~\"voice-registrar.*\",namespace=\"voice\"})) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"voice-registrar.*\", image!=\"\",namespace=\"voice\"}[5m])) /( sum by(pod)(kube_pod_container_resource_requests_cpu_cores{pod=~\"voice-registrar.*\",namespace=\"voice\"}))) * 100"
    }
   ]
  },
  {
   "title": "Registrar_config_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "registrar_config_request", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "registrar_config_request_error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "registrar_config_request_error", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Registrar request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(registrar_request_latency_sum{pod=~\"voice-registrar.*\",namespace=\"voice\"}[1m])/rate(registrar_request_latency_count{pod=~\"voice-registrar.*\",namespace=\"voice\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Registrar_ignored_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "registrar_ignored_request", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Aggregated Service Health State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "registrar_health_level", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Aggregated Service Health Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "registrar_health_check_error", "legendFormat": "{{pod}}:reason-{{reason}}" }
   ]
  }
 ]
}