{
 "title": "Voicemail dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Voicemail Request Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(voicemail_tui_request_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Overall Voicemail Call Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (voicemail_access_call_rate{container=\"voice-voicemail\",namespace=\"voice\"})",
     "legendFormat": "Access Call Rate"
    },
    {
     "expr": "sum by (container) (voicemail_deposit_call_rate{container=\"voice-voicemail\",namespace=\"voice\"})",
     "legendFormat": "Deposit Call Rate"
    }
   ]
  },
  {
   "title": "Storage Access Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(voicemail_storage_request_passed_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "Storage Request Passed"
    },
    {
     "expr": "sum by (container) (rate(voicemail_storage_request_failed_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "Storage Request Failed"
    },
    {
     "expr": "sum by (container) (rate(voicemail_storage_request_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "Storage Request Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (container_memory_working_set_bytes{pod=~\"voice-voicemail.*\",image!=\"\",namespace=\"voice\"}) / sum by(pod)(kube_pod_container_resource_limits_memory_bytes{pod=~\"voice-voicemail.*\",namespace=\"voice\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"voice-voicemail.*\", image!=\"\",namespace=\"voice\"}[5m])) /( sum by(pod)(kube_pod_container_resource_requests_cpu_cores{pod=~\"voice-voicemail.*\",namespace=\"voice\"}))) * 100"
    }
   ]
  },
  {
   "title": "Storage Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (voicemail_storage_alive{container=\"voice-voicemail\",namespace=\"voice\"})",
     "legendFormat": "Storage failures"
    }
   ]
  },
  {
   "title": "Storage Account Average Latency ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) ((voicemail_storage_access_latency_sum{container=\"voice-voicemail\",namespace=\"voice\"}) / (voicemail_storage_access_latency_count{container=\"voice-voicemail\",namespace=\"voice\"}))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Config Node Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(voicemail_config_request_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "Config Request Total"
    },
    {
     "expr": "sum by (container) (rate(voicemail_config_request_failed_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "Config Request Failed"
    }
   ]
  },
  {
   "title": "Consul Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(voicemail_consul_request_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "Consul Request Total"
    },
    {
     "expr": "sum by (container) (rate(voicemail_consul_request_failed_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "Consul Request Failed"
    }
   ]
  },
  {
   "title": "GWS Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(voicemail_gws_request_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "GWS Request Total"
    },
    {
     "expr": "sum by (container) (rate(voicemail_gws_request_failed_total{container=\"voice-voicemail\",namespace=\"voice\"}[1m]))",
     "legendFormat": "GWS Request Failed"
    }
   ]
  }
 ]
}