{
 "title": "DialPlan",
 "tags": [ "voice_common" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Dailplan Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(dialplan_total_request{container=\"voice-dialplan\",namespace=\"voice\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Overall DialPlan Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (dialplan_failure_response{container=\"voice-dialplan\",namespace=\"voice\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "DialPlan Success Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (dialplan_success_response{container=\"voice-dialplan\",namespace=\"voice\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (container_memory_working_set_bytes{pod=~\"voice-dialplan.*\",image!=\"\",namespace=\"voice\"}) / sum by(pod)(kube_pod_container_resource_limits_memory_bytes{pod=~\"voice-dialplan.*\",namespace=\"voice\"})) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"voice-dialplan.*\", image!=\"\",namespace=\"voice\"}[5m])) /( sum by(pod)(kube_pod_container_resource_requests_cpu_cores{pod=~\"voice-dialplan.*\",namespace=\"voice\"}))) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DialPlan Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(dialplan_response_time_sum{pod=~\"voice-dialplan.*\",namespace=\"voice\"}[1m])/rate(dialplan_response_time_count{pod=~\"voice-dialplan.*\",namespace=\"voice\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "log_output_bytes_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(rate(log_output_bytes_total{container=\"voice-dialplan\",format=\"json\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dialplan_redis_state{container=\"voice-dialplan\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Aggregated Service Health State",
   "type": "graph",
   "description": "Check envoy sidecar and redis connection health",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dialplan_health_level", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Aggregated Service Health Errors",
   "type": "graph",
   "description": "Errors in envoy sidecar and redis connection health",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dialplan_health_check_error", "legendFormat": "{{pod}}:reason={{reason}}" }
   ]
  }
 ]
}