{
 "title": "Voice / Redis Queue Service",
 "tags": [
  "voice",
  "rq",
  "voice_common"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (container_memory_working_set_bytes{pod=~\"voice-rq.*\",image!=\"\",namespace=\"voice\"}) / sum by(pod)(kube_pod_container_resource_limits_memory_bytes{pod=~\"voice-rq.*\",namespace=\"voice\"})) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"voice-rq.*\", image!=\"\",namespace=\"voice\"}[5m])) /( sum by(pod)(kube_pod_container_resource_requests_cpu_cores{pod=~\"voice-rq.*\",namespace=\"voice\"}))) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rqnode_redis_state", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Rate of XADDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(rqnode_xadds[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Number of active streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rqnode_streams", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Rate of sent messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rqnode_messages_sent[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RQ latency by ORS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (rate(orsnode_rq_latency_msec_sum[1m])))/(sum by (pod) (rate(orsnode_rq_latency_msec_count[1m])))",
     "legendFormat": "by {{pod}}"
    }
   ]
  },
  {
   "title": "Rate of XREADs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(rqnode_xreads[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Number of clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rqnode_clients", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}