{
 "title": "Config Node Dashboard",
 "tags": [
  "voice",
  "config_node",
  "voice_common"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "config_redis_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "config_redis_state{container=\"voice-config\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "config_node_request_duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(config_config_response_time_sum{container=\"voice-config\"} [1m]) /rate(config_config_response_time_count{container=\"voice-config\"} [1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (container_memory_working_set_bytes{pod=~\"voice-config.*\",image!=\"\",namespace=\"voice\"}) / sum by(pod)(kube_pod_container_resource_limits_memory_bytes{pod=~\"voice-config.*\",namespace=\"voice\"})) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"voice-config.*\", image!=\"\",namespace=\"voice\"}[5m])) /( sum by(pod)(kube_pod_container_resource_requests_cpu_cores{pod=~\"voice-config.*\",namespace=\"voice\"}))) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (rate(config_device_request[1m]))) + (sum by(pod) (rate(config_tenant_request[1m]))) + (sum by(pod) (rate(config_node_get_request[1m])))",
     "legendFormat": " {{ pod }}"
    }
   ]
  },
  {
   "title": "Request Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(config_device_response{status != \"200\"})",
     "legendFormat": "config_device_response -{{ pod }}"
    },
    {
     "expr": "sum by(pod) (config_tenant_response{status != \"200\"})",
     "legendFormat": "config_tenant_response -{{ pod }}"
    },
    {
     "expr": "sum by(pod) (config_node_get_response{status != \"200\"})",
     "legendFormat": "config_node_get_response {{ pod }}"
    }
   ]
  },
  {
   "title": "log_output_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(rate(log_output_bytes_total{container=\"voice-config\",format=\"json\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}