{
 "title": "Voice / SIP Proxy / Alerts",
 "tags": [
  "sipproxy",
  "alerts",
  "voice"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka producer queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_queue_depth{container=\"voice-sipproxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Current state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active sip_nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxy_active_sip_nodes_count{pod!~\"itest.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SIP nodes capacity availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxy_sip_node_is_capacity_available{pod!~\"itest.*\"}",
     "legendFormat": "{{pod}}-{{sip_node_id}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "sip-node response latency 95 percentile, sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sipproxy_response_latency_bucket{request_direction=\"to\",node_in_cache=\"1\"}[5m])) by (le,sip_node_id,pod))",
     "legendFormat": "{{pod}} -> {{sip_node_id}}"
    }
   ]
  },
  {
   "title": "Target latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sipproxy_response_latency_bucket{request_direction!=\"to\"}[5m])) by (le,pod,target))",
     "legendFormat": "{{pod}} - {{target}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Config service error response rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_client_response_count{container=\"voice-sipproxy\",status!~\"2XX\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}