{
 "title": "GCXI / Pods",
 "tags": [ "gcxi" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "NAMESPACE", "label": "Namespace", "query": "gcxi" },
   { "name": "DEPLOYMENT_CODE", "label": "Deployment Code", "query": "gcxi" },
   { "name": "CHART", "label": "Chart", "query": "gcxi" },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-[\\\\d]+-(green|blue)-[\\\\d]$\"},pod)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$NAMESPACE\", pod=~\"$Pod\"}, container)"
   },
   {
    "name": "tenantId",
    "label": "Tenant Id",
    "query": "label_values(kube_statefulset_labels{namespace=\"$NAMESPACE\", statefulset=~\"$DEPLOYMENT_CODE-[\\\\d]+-(green|blue)$\"},label_tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas Ready",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(kube_statefulset_status_replicas_ready{namespace=\"gcxi\",statefulset=~\"gcxi-[\\\\d]+-(blue|green)$\"}) by (statefulset)",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Images Deployed",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$NAMESPACE\", pod=~\"$Pod\"}) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$NAMESPACE\", pod=~\"$Pod\"})[1m]",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container Last Terminated",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_terminated_reason{namespace=\"$NAMESPACE\",pod=~\"$Pod\"}[$__interval])) by (pod,reason) >0"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=\"$NAMESPACE\",pod=~\"$Pod\"}) by (pod,reason) ",
     "legendFormat": "{{ pod }} - {{ reason }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"$Pod\"}[2m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$NAMESPACE\",pod=~\"$Pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$NAMESPACE\", pod=~\"$Pod\"}[2m])))",
     "legendFormat": "RX: {{ pod }}"
    },
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$NAMESPACE\", pod=~\"$Pod\"}[2m])))",
     "legendFormat": "TX: {{ pod }}"
    }
   ]
  }
 ]
}