{
 "title": "GCXI / Health",
 "tags": [ "gcxi" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Test Report Result Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(gcxi__projects__status{namespace=\"gcxi\",service!~\"gcxi-mstr.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cluster Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gcxi__cluster__info{namespace=\"gcxi\",service!~\"gcxi-mstr.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "5xx Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(nginx_ingress_controller_requests{ingress=~\"gcxi-.*\",status=~\"5.*\"}[2m])) by (exported_service) / sum(rate(nginx_ingress_controller_requests{ingress=~\"gcxi-.*\"}[2m])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60 * sum(rate(nginx_ingress_controller_requests{ingress=~\"gcxi-.*\"}[1m])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  }
 ]
}