{
 "title": "gvp-rm-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RM Pod Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RM current inbound Calls per tenant",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rmTenantCurrentInboundCalls{pod=~\"gvp-rm-(0|1)\"}) by (rmTenantName,pod)"
      }
     ]
    },
    {
     "title": "RM container CPU utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((sum(rate(container_cpu_usage_seconds_total{container=\"gvp-rm\",pod=~\"gvp-rm-(0|1)\"}[5m])) by (pod))/(sum(container_spec_cpu_quota{container=\"gvp-rm\",pod=~\"gvp-rm-(0|1)\"}/container_spec_cpu_period{container=\"gvp-rm\",pod=~\"gvp-rm-(0|1)\"}) by (pod))) * 100"
      }
     ]
    },
    {
     "title": "RM container memory utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(container_memory_usage_bytes{pod=~\"gvp-rm-(0|1)\",container=\"gvp-rm\"}) by (pod)/sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"gvp-rm-(0|1)\",container=\"gvp-rm\"}) by (pod)) * 100"
      }
     ]
    },
    {
     "title": "RM Total 4xx errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (idelta(rmTotal4xxInviteSent{pod=~\"gvp-rm-(0|1)\"}[30s]))"
      }
     ]
    },
    {
     "title": "RM Total 5xx errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rmTotal5xxInviteSent{pod=~\"gvp-rm-(0|1)\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "RM-MCP Status Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "MCP availability",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(rmPRStatus{pod=\"gvp-rm-0\",rmPRStatus=~\"(AVAILABLE)\"}) BY (POD)",
       "legendFormat": " MCP Online"
      },
      {
       "expr": "SUM(rmPRStatus{pod=\"gvp-rm-0\",rmPRStatus=\"UNAVAILABLE\"}) BY (POD)",
       "legendFormat": "MCP Offline"
      }
     ]
    },
    {
     "title": "% MCP Availability",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(((count(rmPRStatus{pod=\"gvp-rm-0\",rmPRStatus=\"AVAILABLE\"}) by (pod))) / (count(rmPRName{pod=\"gvp-rm-0\"}) by (pod)))*100 ",
       "legendFormat": "% MCP available"
      },
      {}
     ]
    },
    {
     "title": "RM Pod Status",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_status_ready{namespace=\"gvp\", container=\"gvp-rm\", pod=~\"gvp-rm-(0|1)\"}))"
      }
     ]
    },
    {
     "title": "MCP Status - Available",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rmPRStatus{pod=\"gvp-rm-0\",rmPRStatus=\"AVAILABLE\"}) by (rmPRName)",
       "legendFormat": "{{rmPRName}} AVAILABLE"
      }
     ]
    },
    {
     "title": "MCP Status Unavailable",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rmPRStatus{pod=\"gvp-rm-0\",rmPRStatus=\"UNAVAILABLE\"}) by (rmPRName)",
       "legendFormat": "{{rmPRName}} UNAVAILABLE"
      }
     ]
    },
    {
     "title": "% MCP Availability from MCP Replicas Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(rmPRStatus{pod=\"gvp-rm-0\",rmPRStatus=\"AVAILABLE\"}) by (pod)/sum(kube_statefulset_status_replicas_current{namespace=\"gvp\", statefulset=~\"gvp-mcp-pipe-(blue|green)\"})*100",
       "legendFormat": "% MCP available"
      }
     ]
    },
    {
     "title": "MCP Active Calls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rmPRActiveCalls{pod=\"gvp-rm-0\"}) by (rmPRName)",
       "legendFormat": "{{rmPRName}}"
      }
     ]
    },
    {
     "title": "MCP Total Calls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rmPRTotalCalls{pod=\"gvp-rm-0\"}) by (rmPRName)",
       "legendFormat": "{{rmPRName}}"
      }
     ]
    }
   ]
  }
 ]
}