{
 "title": "Azure MCP Utilization - gvp-mcp",
 "description": "Display various utilization data for the GVP/MCP pods",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "MCP Service Health",
   "type": "gauge",
   "description": "Computes MCP service availability by comparing  the pods which are ready with the the total pods expected as per the desired replica count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(count(kube_pod_container_status_ready{namespace=\"gvp\", container=\"gvp-mcp\", pod=~\"gvp-mcp.*\"} == 1)/sum(kube_statefulset_status_replicas_current{namespace=\"gvp\", statefulset=~\"gvp-mcp.*\"})* 100)"
    }
   ]
  },
  {
   "title": "MCP POD Container Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"gvp\", container=\"gvp-mcp\", pod=~\"gvp-mcp.*\"}[15m])",
     "legendFormat": " {{ pod }} "
    }
   ]
  },
  {
   "title": "Number of MCP replicas",
   "type": "graph",
   "description": "Number of replicas in the MCP stateful sets",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_current{namespace=\"gvp\",statefulset=~\"gvp-mcp.*\"}",
     "legendFormat": " {{ statefulset }} "
    }
   ]
  },
  {
   "title": "MCP Current Inbound Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "mcpSipCurrentInboundSessions{pod=~\"gvp-mcp.*\",container=\"mcp-snmp\"}",
     "legendFormat": " {{ pod }} "
    }
   ]
  },
  {
   "title": "MCP Container Memory Use %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod=~\"gvp-mcp.*\",container=\"gvp-mcp\"}) by (pod)/sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"gvp-mcp.*\",container=\"gvp-mcp\"}) by (pod)) * 100",
     "legendFormat": " {{ pod }} "
    }
   ]
  },
  {
   "title": "MCP Container Working Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"gvp-mcp.*\",container=\"gvp-mcp\"}/1e9",
     "legendFormat": " {{ pod }} "
    }
   ]
  },
  {
   "title": "MCP Container CPU Use %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",pod=~\"gvp-mcp.*\",container=\"gvp-mcp\"}[5m]) ) by (pod) / (sum(container_spec_cpu_quota{container=\"gvp-mcp\", pod=~\"gvp-mcp.*\"}/container_spec_cpu_period{container=\"gvp-mcp\", pod=~\"gvp-mcp.*\"}) by (pod)) * 100",
     "legendFormat": " {{ pod }} "
    }
   ]
  },
  {
   "title": "Persistent Volume Available Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  sum (kubelet_volume_stats_available_bytes{namespace=\"gvp\", persistentvolumeclaim=~\".*gvp-mcp.*\"}) by(persistentvolumeclaim)\n  /\n  sum (kubelet_volume_stats_capacity_bytes{namespace=\"gvp\", persistentvolumeclaim=~\".*gvp-mcp.*\"}) by(persistentvolumeclaim)\n) * 100",
     "legendFormat": " {{ persistentvolumeclaim }} "
    }
   ]
  },
  {
   "title": "Network Transmit Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"gvp\", pod=~\"gvp-mcp.*\"}[5m])) by (pod)",
     "legendFormat": " {{ pod }} "
    }
   ]
  },
  {
   "title": "Network Receive Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"gvp\", pod=~\"gvp-mcp.*\"}[5m])) by (pod)",
     "legendFormat": " {{ pod }} "
    }
   ]
  }
 ]
}