{
 "title": "MCP Log Alerts - gvp-mcp",
 "description": "Alerts for GVP services based on logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "MCP Service Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(kube_pod_container_status_ready{namespace=\"gvp\", container=\"gvp-mcp\", pod=~\"gvp-mcp.*\"} == 1)/sum(kube_statefulset_status_replicas_current{namespace=\"gvp\", statefulset=~\"gvp-mcp.*\"})* 100)"
    }
   ]
  },
  {
   "title": "MCP Start Recording Errors - Critical",
   "type": "graph",
   "description": "Number of errors starting GIR or IVR recording exceeded limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"Unable to start recording\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MCP DNS Resolution Failures",
   "type": "graph",
   "description": "Number of DNS resolution failures has exceeded specified limit.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"Request\" AND log_source.message:\"failed\" AND log_source.message:\"result\" AND log_source.message:\"6\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MCP DTMF Grammar Errors",
   "type": "graph",
   "description": "There are errors with the DTMF grammar.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"EROR\" AND log_source.message:\"grammar\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MCP SIPp Self-Test Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "( k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"service-handler\" AND log: \"sipp call failed\" )",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MCP Total Errors",
   "type": "graph",
   "description": "Number of EROR log entries ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"EROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MCP exec errors",
   "type": "graph",
   "description": "Number of exec_errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"exec_error\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MCP Fetch Errors",
   "type": "graph",
   "description": "Number of Fetch errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "4xx fetch errors",
     "bucketAggs": [
      {
       "$$hashKey": "object:218",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:216", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"EROR\" AND log_source.message:\"40032\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Fetch errors",
     "bucketAggs": [
      {
       "$$hashKey": "object:222",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:220", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"EROR\" AND log_source.message:\"40027\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MCP Configserver Disconnect",
   "type": "graph",
   "description": "Number of Configserver disconnect",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:539",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:537",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "k8s_pod_name: \"gvp-mcp\" AND k8s_container_name: \"mcp-snmp\" AND log_source.message:\"connection to Configuration Server is lost\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}