{
 "title": "Job Scheduler ",
 "description": "Job Scheduler",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "pod",
    "query": "up{namespace=\"$namespace\",job=\"$service\"}"
   },
   {
    "name": "type",
    "label": "Job Type",
    "query": "cxc_js_jobs_executed_total{service=\"$service\"}"
   },
   { "name": "service", "query": "cxc-job-scheduler" },
   { "name": "namespace", "query": "cxc" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "destination",
    "query": "cxc_js_request_out_count{service=\"$service\"}"
   },
   {
    "name": "tenant_name",
    "query": "cxc_js_jobs_executed_total{service=\"$service\"}"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Scheduler instances:",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cxc_js_healthy_instance{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$service.*\"}[5m])*5*60",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Job Scheduler",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(cxc_js_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "JS Healthy Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_js_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Redis Connection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cxc_js_redis_connections{service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Jobs success total per 1m $pod, job - $type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_js_jobs_success_total{pod=~\"$pod\", type=~\"$type\", service=\"$service\"}[1m])) by (tenant_name,type)",
     "legendFormat": "{{ tenant_name }}: {{ type }}"
    }
   ]
  },
  {
   "title": "Jobs running total $pod $type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_js_jobs_running_total{pod=~\"$pod\", type=~\"$type\", service=\"$service\"}) by (type,tenant_name)",
     "legendFormat": "{{ tenant_name }} {{ type }}"
    }
   ]
  },
  {
   "title": "Jobs failed total per $interval $pod $type $tenant_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_js_jobs_failed_total{pod=~\"$pod\", type=~\"$type\",service=\"$service\"}[$interval])) by (tenant_name,type)",
     "legendFormat": "{{ tenant_name }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Job duration seconds bucket $pod $type $le",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(cxc_js_job_duration_seconds_bucket{pod=~\"$pod\",type=~\"$type\",service=\"$service\"}[25s])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Jobs executed per 1h $pod $type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_js_jobs_executed_total{pod=~\"$pod\", type=~\"$type\",service=\"$service\"}[1h])) by (tenant_name,type)",
     "legendFormat": "{{ tenant_name }}: {{ type }}"
    }
   ]
  },
  {
   "title": "Jobs run now total($pod)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cxc_js_jobs_run_now_total{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "{{ pod }} {{ type }}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Ingress Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"2..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"3..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"4..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"5..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Requests  - Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method)(\n    rate(cxc_js_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method, Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method,path, code)(\n    rate(cxc_js_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": " {{ path }} {{ method }} {{ code }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_js_request_count{pod=~\"$pod\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_js_request_count{pod=~\"$pod\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_js_request_count{pod=~\"$pod\", code=~\"3..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(cxc_js_request_count{pod=~\"$pod\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le)(\n    rate(cxc_js_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) "
    }
   ]
  },
  { "title": "Requests - Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method, destination)(\n    rate(cxc_js_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"3..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "3xx"
    }
   ]
  },
  {
   "title": "Request Count pod: $pod per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_js_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])) by (method,code,destination)",
     "legendFormat": "{{ method }} {{ destination }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le, destination)(\n    rate(cxc_js_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n    )\n)",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}