{
 "title": "API Aggregator ",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "up{namespace=\"cxc\",job=\"$service\"}"
   },
   {
    "name": "tenant_name",
    "label": "Tenant Name",
    "query": "cxc_api_aggregator_users_logged_in_total{service=\"$service\"}"
   },
   { "name": "service", "query": "$service" },
   { "name": "namespace", "query": "cxc" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "destination",
    "query": "cxc_api_aggregator_request_out_count{service=\"$service\"}"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Aggregator  instances:",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cxc_api_healthy_instance{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$service.*\"}[5m])*5*60",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "cxc_api_healthy_instance",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cxc_api_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "cxc_api_healthy_instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_api_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Redis Connection Error",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cxc_api_aggregator_redis_connection{service=\"$service\"}"
    }
   ]
  },
  { "title": "Active Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Users Tenant: $tenant_name",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(cxc_api_aggregator_users_logged_in_total{tenant_name=~\"$tenant_name\",service=\"$service\"}[12h]))  - sum(increase(cxc_api_aggregator_users_logged_out_total{tenant_name=~\"$tenant_name\",service=\"$service\"}[12h]))",
     "legendFormat": "Active Users "
    }
   ]
  },
  {
   "title": "Current Active Users Per Tenant",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "topk(5,sum(increase(cxc_api_aggregator_users_logged_in_total{service=\"$service\"}[12h])) by (tenant_name)  - sum(increase(cxc_api_aggregator_users_logged_out_total{}[12h])) by (tenant_name))",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Users. Tenant: $tenant_name",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(cxc_api_aggregator_users_logged_in_total{tenant_name=~\"$tenant_name\",service=\"$service\"}[12h]))",
     "legendFormat": "Users logged in total"
    },
    {
     "expr": "sum(increase(cxc_api_aggregator_users_logged_out_total{tenant_name=~\"$tenant_name\",service=\"$service\"}[12h]))",
     "legendFormat": "Users logged out total "
    }
   ]
  },
  {
   "title": "Campaign Templates. Pod: $pod  Tenant: $tenant_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cxc_api_aggregator_campaign_template_removed_total{pod=~\"$pod\",tenant_name=~\"$tenant_name\",service=\"$service\"})[$interval]",
     "legendFormat": "REMOVED {{ tenant_name }}"
    },
    {
     "expr": "increase(cxc_api_aggregator_campaign_template_created_total{pod=~\"$pod\",tenant_name=~\"$tenant_name\",service=\"$service\"})[$interval]",
     "legendFormat": "CREATED {{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Users Per Tenant",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,(sum(increase(cxc_api_aggregator_users_logged_in_total{service=\"$service\"}[12h])) by (tenant_name)))",
     "legendFormat": "In {{ tenant_name }}"
    },
    {
     "expr": "topk(10,(sum(increase(cxc_api_aggregator_users_logged_out_total{service=\"$service\"}[12h])) by (tenant_name)))",
     "legendFormat": "Out {{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_api_aggregator_users_logged_in_total{tenant_name=~\"$tenant_name\"}[12h])) by (tenant_name) - sum(increase(cxc_api_aggregator_users_logged_out_total{tenant_name=~\"$tenant_name\"}[12h])) by (tenant_name)",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Ingress Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"2..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"3..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"4..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"500\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"502\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"504\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Requests - Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Request Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m]))",
     "legendFormat": "nginx-ingress"
    },
    {
     "expr": "sum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", service=\"$service\"}[1m]))\n",
     "legendFormat": "service"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le,method)(\n    rate(cxc_api_aggregator_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method, Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method,path, code)(\n    rate(cxc_api_aggregator_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": " {{ path }} {{ method }} {{ code }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", code=~\"3..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_api_aggregator_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "API requests. Tenant: $tenant_name  Pod: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(increase(cxc_api_aggregator_top_api_requests{service=\"$service\"}[1m])) by (path,tenant_name))",
     "legendFormat": "{{ tenant_name }} {{ path }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le)(\n    rate(cxc_api_aggregator_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) "
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_api_aggregator_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_api_aggregator_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_api_aggregator_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_api_aggregator_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_api_aggregator_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_api_aggregator_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Requests - Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Request Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_api_aggregator_request_out_count{pod=~\"$pod\", service=\"$service\"}[1m])) by (destination)\n ",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method, destination)(\n    rate(cxc_api_aggregator_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Request Count $pod with interval $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_api_aggregator_request_out_count{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])) by (method,code,destination)",
     "legendFormat": "{{ method }} {{ destination }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le, destination)(\n    rate(cxc_api_aggregator_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n    )\n)",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Process HEAP $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cxc_api_aggregator_process_heap_bytes{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "Process heap bytes {{ pod }}"
    }
   ]
  },
  {
   "title": "Process CPU $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_api_aggregator_process_cpu_seconds_total{pod=~\"$pod\",service=\"$service\"}[30s]) * 100) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Process MEMORY $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cxc_api_aggregator_process_resident_memory_bytes{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "Process resident memory bytes {{ pod }}"
    },
    {
     "expr": "cxc_api_aggregator_process_virtual_memory_bytes{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "Process virtual memory bytes {{ pod }}"
    }
   ]
  },
  {
   "title": "NodeJS Heap space $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_api_aggregator_nodejs_heap_space_size_available_bytes{pod=~\"$pod\",service=\"$service\"}) by (pod)",
     "legendFormat": "HEAP space size available bytes ({{ pod }})"
    },
    {
     "expr": "sum(cxc_api_aggregator_nodejs_heap_space_size_total_bytes{pod=~\"$pod\",service=\"$service\"}) by (pod)",
     "legendFormat": "HEAP space size total bytes ({{ pod }})"
    },
    {
     "expr": "sum(cxc_api_aggregator_nodejs_heap_space_size_used_bytes{pod=~\"$pod\",service=\"$service\"}) by (pod)",
     "legendFormat": "HEAP space size used bytes ({{ pod }})"
    }
   ]
  },
  {
   "title": "NodeJS eventloop lag seconds $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cxc_api_aggregator_nodejs_eventloop_lag_seconds{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "NodeJS evetloop lag seconds {{ pod }}"
    }
   ]
  },
  {
   "title": "process_open_fds / process_max_fds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cxc_api_aggregator_process_open_fds{pod=~\"$pod\",service=\"$service\"} / cxc_api_aggregator_process_max_fds{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Process NodeJS requests $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cxc_api_aggregator_nodejs_active_requests_total{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "NodeJS total active requests {{ pod }}"
    }
   ]
  },
  {
   "title": "Process NodeJS handles $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cxc_api_aggregator_nodejs_active_handles_total{pod=~\"$pod\",service=\"$service\"}",
     "legendFormat": "NodeJS active handles total {{ pod }}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 } },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 196 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}