{
 "title": "List Manager ",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "pod",
    "query": "up{namespace=\"$namespace\",job=\"$service\"}"
   },
   {
    "name": "method",
    "label": "Request Method",
    "query": "cxc_list_manager_responses_summary_count{service=\"$service\"}"
   },
   {
    "name": "status",
    "label": "Response Status",
    "query": "cxc_list_manager_responses_summary_count{service=\"$service\"}"
   },
   {
    "name": "path",
    "label": "Request path",
    "query": "cxc_list_manager_responses_summary_count{service=\"$service\"}"
   },
   {
    "name": "tenant_name",
    "label": "Tenant Name",
    "query": "cxc_list_manager_contacts_lists_created_count{service=\"$service\"}"
   },
   {
    "name": "ccid",
    "label": "CCID",
    "query": "cxc_list_manager_contacts_lists_created_count{service=\"$service\"}"
   },
   { "name": "service", "query": "cxc-list-manager" },
   { "name": "namespace", "query": "cxc" },
   {
    "name": "destination",
    "query": "cxc_list_manager_request_out_total{service=\"$service\"}"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "List Manager pods:",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cxc_list_manager_healthy_instance{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$service.*\"}[5m])*5*60",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "List Manager",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(cxc_list_manager_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "LM healthy pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_list_manager_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Contact Lists Created | pod: $pod | tenant: $tenant_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_list_manager_contacts_lists_created_count{pod=~\"$pod\", service=\"$service\"}[10m])) by (tenant_name, ccid)",
     "legendFormat": "{{ tenant_name }} | ccid: {{ ccid }}"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cxc_list_manager_running_jobs_count{pod=~\"$pod\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Running Jobs | pod: $pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_list_manager_running_jobs_count{pod=~\"$pod\",service=\"$service\"}) by (pod)",
     "legendFormat": "Running jobs count {{ pod }}"
    }
   ]
  },
  {
   "title": "Compliance Files Jobs Result",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_list_manager_executed_jobs_count{pod=~\"$pod\",service=\"$service\"}[10m]))",
     "legendFormat": "Executed jobs"
    },
    {
     "expr": "sum(increase(cxc_list_manager_downloaded_compliance_files_count{pod=~\"$pod\",service=\"$service\"}[10m]))",
     "legendFormat": "Downloaded Files"
    }
   ]
  },
  {
   "title": "Jobs Duration | pod: $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(cxc_list_manager_jobs_duration_bucket{pod=~\"$pod\",service=\"$service\"}[10m])) by (le))"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Ingress Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"2..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"3..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"4..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"500\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"502\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"504\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Requests - Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method)(\n    rate(cxc_list_manager_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": " {{ path }} {{ method }} {{ code }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method, Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method,path, code)(\n    rate(cxc_list_manager_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": " {{ path }} {{ method }} {{ code }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_list_manager_request_count{pod=~\"$pod\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_list_manager_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_list_manager_request_count{pod=~\"$pod\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_list_manager_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_list_manager_request_count{pod=~\"$pod\", code=~\"3..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_list_manager_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(cxc_list_manager_request_count{pod=~\"$pod\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_list_manager_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le)(\n    rate(cxc_list_manager_request_latencies_ms_bucket{pod=~\"$pod\", service=\"$service\"}[$interval])\n  )\n) "
    }
   ]
  },
  { "title": "Requests - Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method, destination)(\n    rate(cxc_list_manager_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_list_manager_request_out_total{pod=~\"$pod\", destination=~\"$destination\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_list_manager_request_out_total{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_list_manager_request_out_total{pod=~\"$pod\", destination=~\"$destination\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_list_manager_request_out_total{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_list_manager_request_out_total{pod=~\"$pod\", destination=~\"$destination\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_list_manager_request_out_total{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Count pod: $pod per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_list_manager_request_out_total{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])) by (method,code,destination)",
     "legendFormat": "{{ method }} {{ destination }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le, destination)(\n    rate(cxc_list_manager_request_out_latencies_ms_bucket{pod=~\"$pod\", destination=~\"$destination\", service=\"$service\"}[$interval])\n    )\n)",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}