{
 "title": "Dial Manager",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "up{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",namespace=\"$namespace\",job=\"$service\"}"
    }
   },
   {
    "name": "media",
    "query": {
     "query": "cxc_dm_delivery_buffer_size{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\"}"
    }
   },
   {
    "name": "tenant_name",
    "query": {
     "query": "cxc_dm_processed_batches_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\"}"
    }
   },
   { "name": "service", "query": "cxc-dial-manager" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "cxc" },
   {
    "name": "destination",
    "query": {
     "query": "cxc_dm_request_out_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\"}"
    }
   },
   { "name": "cloud", "query": { "query": "up{}" } },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "up{environment=\"${environment}\"}"
    }
   },
   {
    "name": "environment",
    "query": {
     "query": "up{cloud=\"${cloud}\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dial Manager pods:",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cxc_dm_healthy_instance{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",namespace=\"$namespace\", pod=~\"$service.*\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Dial Manager",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(cxc_dm_healthy_instance{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\"})"
    }
   ]
  },
  {
   "title": "DM healthy pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_dm_healthy_instance{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\"})"
    }
   ]
  },
  { "title": "Dial Manager Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Delivery Buffer Size. Media: $media Pod: $pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(cxc_dm_delivery_buffer_size{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\", media=~\"$media\"}) by (media)",
     "legendFormat": "{{ media }}"
    }
   ]
  },
  {
   "title": "Processed Batches Total $pod, $tenant_name, $media",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_dm_processed_batches_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\", media=~\"$media\"}) by (tenant_name,media) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} - {{ media }}"
    }
   ]
  },
  {
   "title": "Process Message Duration Seconds $pod, $tenant_name, $media",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(cxc_dm_process_message_duration_seconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\", media=~\"$media\"}[$interval])) by (le,tenant_name,media)) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} - {{ media }}"
    }
   ]
  },
  {
   "title": "Processed Messages Total $pod, $tenant_name, $media",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_dm_processed_messages_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\", media=~\"$media\"}[$interval])) by (tenant_name,media) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} - {{ media }}"
    }
   ]
  },
  {
   "title": "Batch Size $pod, $tenant_name, $media",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(cxc_dm_batch_size_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\", media=~\"$media\"}[$interval])) by (le,tenant_name,media)) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} - {{ media }}"
    }
   ]
  },
  {
   "title": "Failed Processed Messages per $interval $pod, $tenant_name, $media",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_dm_failed_processed_messages_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\", media=~\"$media\"}[$interval])) by (tenant_name,media) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} - {{ media }}"
    }
   ]
  },
  {
   "title": "Test Messages per $interval $pod, $tenant_name, $media",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_dm_test_messages_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\", media=~\"$media\"}[$interval])) by (tenant_name, media) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} - {{ media }}"
    }
   ]
  },
  {
   "title": "Failed Test Messages per $interval $pod, $tenant_name, $media",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_dm_failed_test_messages_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\", media=~\"$media\"}[$interval])) by (tenant_name, media) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} - {{ media }}"
    }
   ]
  },
  {
   "title": "Nexus Service Status $pod, $tenant_name",
   "type": "graph",
   "description": "Returns 0 if there is no connections to nexus or number of established connections. The max number of connections described by option socketPoolSize in dial section",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cxc_dm_nexus_service_status{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\",tenant_name=~\"$tenant_name\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Ingress Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\", exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"2..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\", exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"3..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\", exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"4..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\", exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"500\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\", exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"502\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\", exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"504\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\", exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Requests - Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Request Latency by Tenant Name and Media Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n 0.90,\n sum by (le,media,tenant_name)(\n rate(cxc_dm_request_latencies_ms_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\"}[$interval])\n )\n) ",
     "legendFormat": "{{ tenant_name }} {{ media }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method, Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n 0.80,\n sum by (le, media,tenant_name, code)(\n rate(cxc_dm_request_latencies_ms_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\"}[$interval])\n )\n) ",
     "legendFormat": " {{ tenant_name }} {{ media }} HTTP:{{ code }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval | Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_dm_request_count{pod=~\"$pod\", code=~\"2..\"}[$interval]))\n/\nsum(rate(cxc_dm_request_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_dm_request_count{pod=~\"$pod\", code=~\"4..\"}[$interval]))\n/\nsum(rate(cxc_dm_request_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_dm_request_count{pod=~\"$pod\", code=~\"3..\"}[$interval]))\n/\nsum(rate(cxc_dm_request_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\"}[$interval]))\n*100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(cxc_dm_request_count{pod=~\"$pod\", code=~\"5..\"}[$interval]))\n/\nsum(rate(cxc_dm_request_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n 0.90,\n sum by (le)(\n rate(cxc_dm_request_latencies_ms_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\"}[$interval])\n )\n) "
    }
   ]
  },
  { "title": "Request - Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n 0.80,\n sum by (le, method, destination)(\n rate(cxc_dm_request_out_latencies_ms_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\", destination=~\"$destination\"}[$interval])\n )\n) ",
     "legendFormat": "{{ method }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval | Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_dm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"2..\"}[$interval]))\n/\nsum(rate(cxc_dm_request_out_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\", destination=~\"$destination\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_dm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"4..\"}[$interval]))\n/\nsum(rate(cxc_dm_request_out_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\", destination=~\"$destination\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_dm_request_out_count{pod=~\"$pod\", destination=~\"$destination\", code=~\"5..\"}[$interval]))\n/\nsum(rate(cxc_dm_request_out_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\", destination=~\"$destination\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Count pod: $pod per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_dm_request_out_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\", destination=~\"$destination\"}[$interval])) by (method,code,destination)",
     "legendFormat": "{{ method }} {{ destination }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n 0.90,\n sum by (le, destination)(\n rate(cxc_dm_request_out_latencies_ms_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",pod=~\"$pod\", destination=~\"$destination\"}[$interval])\n )\n)",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",namespace=\"$namespace\",pod=~\"$service-.*\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",namespace=\"$namespace\",pod=~\"$service-.*\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}