{
 "title": "List Builder ",
 "tags": [
  "cxc",
  ""
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "pod",
    "query": "up{namespace=\"$namespace\",job=\"$service\"}"
   },
   {
    "name": "type",
    "label": "Job Type",
    "query": "cxc_lb_job_duration_seconds_sum{service=\"$service\"}"
   },
   {
    "name": "ccid",
    "label": "ccid",
    "query": "cxc_lb_contacts_imported_total{service=\"$service\"}"
   },
   {
    "name": "tenant_name",
    "label": "Tenant Name",
    "query": "cxc_lb_contacts_imported_total{service=\"$service\"}"
   },
   {
    "name": "http_code",
    "label": "HTTP Code",
    "query": "cxc_lb_request_count{service=\"$service\"}"
   },
   {
    "name": "http_method",
    "label": "HTTP Method",
    "query": "cxc_lb_request_count{service=\"$service\"}"
   },
   {
    "name": "http_path",
    "label": "HTTP Path",
    "query": "cxc_lb_request_count{service=\"$service\"}"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" },
   { "name": "service", "query": "cxc-list-builder" },
   { "name": "namespace", "query": "cxc" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "List Builder Pods:",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cxc_lb_healthy_instance{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$service.*\"}[5m])*5*60",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "List Builder Healthy pods",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(cxc_lb_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "LB healthy pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cxc_lb_healthy_instance{service=\"$service\"})"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Ingress Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"2..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"3..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100 \n",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\", status=~\"4..\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[1m])) \n*100\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"500\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"502\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\", status=~\"504\"}[1m]))\n/\nsum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"cxc-amark-app\"}[1m])) \n*100 \n",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", exported_service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Requests - incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method)(\n    rate(cxc_lb_request_latencies_ms_bucket{pod=~\"$pod\", method=~\"$http_method\", code=~\"$http_code\", path=~\"$http_path\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Request Latency by HTTP Method, Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method,path, code)(\n    rate(cxc_lb_request_latencies_ms_bucket{pod=~\"$pod\", method=~\"$http_method\", code=~\"$http_code\", path=~\"$http_path\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": " {{ path }} {{ method }} {{ code }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_lb_request_count{pod=~\"$pod\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_lb_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_lb_request_count{pod=~\"$pod\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_lb_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_lb_request_count{pod=~\"$pod\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_lb_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(cxc_lb_request_count{pod=~\"$pod\", code=~\"3..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_lb_request_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "3xx"
    }
   ]
  },
  {
   "title": "Request Count $pod $http_code $http_method with interval $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_lb_request_count{pod=~\"$pod\",method=~\"$http_method\",code=~\"$http_code\", path=~\"$http_path\", service=\"$service\"}[$interval])) by (method,code)",
     "legendFormat": "{{ method }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le)(\n    rate(cxc_lb_request_latencies_ms_bucket{pod=~\"$pod\", method=~\"$http_method\", code=~\"$http_code\", path=~\"$http_path\", service=\"$service\"}[$interval])\n  )\n) "
    }
   ]
  },
  { "title": "Requests - outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Request Latency by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.80,\n  sum by (le, method,destination)(\n    rate(cxc_lb_request_out_latencies_ms_bucket{pod=~\"$pod\", method=~\"$http_method\", code=~\"$http_code\", service=\"$service\"}[$interval])\n  )\n) ",
     "legendFormat": "{{ method }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Error Ratio (HTTP) | interval: $interval |  Pod: $pod ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cxc_lb_request_out_count{pod=~\"$pod\", code=~\"2..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_lb_request_out_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cxc_lb_request_out_count{pod=~\"$pod\", code=~\"4..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_lb_request_out_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(cxc_lb_request_out_count{pod=~\"$pod\", code=~\"5..\", service=\"$service\"}[$interval]))\n/\nsum(rate(cxc_lb_request_out_count{pod=~\"$pod\", service=\"$service\"}[$interval]))\n*100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Count $pod $http_code $http_method with interval $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_lb_request_out_count{pod=~\"$pod\",method=~\"$http_method\",code=~\"$http_code\", service=\"$service\"}[$interval])) by (method,code)",
     "legendFormat": "{{ method }} - {{ code }} per {{ $interval }}"
    }
   ]
  },
  {
   "title": "Average Request Latency $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.90,\n  sum by (le, destination)(\n    rate(cxc_lb_request_out_latencies_ms_bucket{pod=~\"$pod\", method=~\"$http_method\", code=~\"$http_code\", service=\"$service\"}[$interval])\n  )\n) "
    }
   ]
  },
  { "title": "Import Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Average Job Duration Seconds $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cxc_lb_job_duration_seconds_bucket{pod=~\"$pod\",tenant_name=~\"$tenant_name\", ccid=~\"$ccid\", type=~\"$type\", service=\"$service\"}[$interval])) by (le))"
    }
   ]
  },
  {
   "title": "Summary Import Jobs Executes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(cxc_lb_job_count{pod=~\"$pod\", tenant_name=~\"$tenant_name\", ccid=~\"$ccid\", type=~\"$type\", service=\"$service\"}[$__range])) by (result)) or on() vector(0) ",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Import Jobs Success/Fail ratio per $interval $pod, $type, $ccid, $tenant_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 110 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum (increase(cxc_lb_job_count{pod=~\"$pod\", type=~\"$type\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", type=~\"$type\", result=\"FAIL\", service=\"$service\"}[$interval]))  OR on() vector(0))\n/\n(sum (increase(cxc_lb_job_count{pod=~\"$pod\", type=~\"$type\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", type=~\"$type\", service=\"$service\"}[$interval]))  OR on() vector(0))\n\n*100",
     "legendFormat": "Fail"
    },
    {
     "expr": "(sum (increase(cxc_lb_job_count{pod=~\"$pod\", type=~\"$type\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", type=~\"$type\", result=\"SUCCESS\", service=\"$service\"}[$interval]))  OR on() vector(0))\n/\n(sum (increase(cxc_lb_job_count{pod=~\"$pod\", type=~\"$type\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", type=~\"$type\", service=\"$service\"}[$interval]))  OR on() vector(0))\n\n*100",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Summary Import Jobs Running",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 119 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cxc_lb_jobs_running_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", ccid=~\"$ccid\", type=~\"$type\", service=\"$service\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Summary Total Contacts Imported",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 124 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(cxc_lb_contacts_imported_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", ccid=~\"$ccid\", type=~\"$type\", service=\"$service\"}[$__range])) OR on() vector(0)\n+\nsum(increase(cxc_lb_rejected_contact_lines_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", ccid=~\"$ccid\", type=~\"$type\", service=\"$service\"}[$__range]))  OR on() vector(0)\n"
    }
   ]
  },
  {
   "title": "Total Contacts imported per $interval $pod $ccid $tenant_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 4, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_lb_contacts_imported_total{pod=~\"$pod\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) by (tenant_name,ccid) or on() vector(0)",
     "legendFormat": "{{ tenant_name }} Imported "
    },
    {
     "expr": "sum(increase(cxc_lb_rejected_contact_lines_total{pod=~\"$pod\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", service=\"$service\"}[$interval])) by (tenant_name,ccid) or on() vector(0)",
     "legendFormat": "{{ tenant_name }}  Rejected"
    }
   ]
  },
  {
   "title": "Current Contacts import speed per minute",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 124 },
   "targets": [
    {
     "expr": "(sum(increase(cxc_lb_contacts_imported_total{pod=~\"$pod\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", service=\"$service\"}[1m])) OR on() vector(0))\n+\n(sum(increase(cxc_lb_rejected_contact_lines_total{pod=~\"$pod\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", service=\"$service\"}[1m])) OR on() vector(0))",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Summary Total Devices Imported",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 131 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(cxc_lb_devices_imported_total{pod=~\"$pod\", tenant_name=~\"$tenant_name\", ccid=~\"$ccid\", type=~\"$type\", service=\"$service\"}[$__range]))  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Devices Imported per $interval $pod $ccid $tenant_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 4, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cxc_lb_devices_imported_total{pod=~\"$pod\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\",service=\"$service\"}[$interval])) by (tenant_name,ccid) or on() vector(0)",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  {
   "title": "Current Devices import speed per minute",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 131 },
   "targets": [
    {
     "expr": "sum(increase(cxc_lb_devices_imported_total{pod=~\"$pod\", ccid=~\"$ccid\", tenant_name=~\"$tenant_name\", service=\"$service\"}[1m]))  OR on() vector(0)",
     "legendFormat": "{{ tenant_name }}"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 4, "y": 138 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{service=\"$service\"}[30s])) by (pod)*100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "The cgroup's CPU usage in the last minute (% of CPU request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"POD\"}[1m])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "The cgroup's total memory usage (in bytes)\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes received over the network by the container per second in the last minute\t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$service-.*\", container!=\"\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}