{
 "title": "Tenants",
 "tags": [ "iwddm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Tenant",
    "query": "label_values(iwddm_job_active,tenant)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "content": "# What should I check if there is no data in GCXI reports for a tenant?\n### Short check\n* If a status is green and last started within 15 minutes - Datamart works, no problem here\n* If a status is red - we have a problem\n* If a status is green but 'intraday' last started more than several hours ago - we have a problem\n\n### Description\n\nThe dashboard shows iWD Datamart status for all tenants where monitoring is set up and working.\n\n**\"All tenants\"** block has overall stats.\n\nFor tenant:\n**\"Job status\"** panel shows last job run result. If it is green - okay. If it is red - we have a problem, need to read logs.\n\n**\"Job schedule\"** panel shows when it was a last time a job started and finished. For `intraday` it should be no longer than 15 minutes ago. For `historical` it should be no longer than 24 hours ago.\n\n**\"Jobs in Active state\"** shows technical information about job duration. For `intraday` it should take no longer than 10 minutes, for `historical` it should take no longer than 1 hour. When job has been running only for several seconds, it might not be shown in the graph.\n"
  },
  { "title": "All tenants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Tenants",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "iwddm_job_last_success{tenant=~\"$Tenant\"} - iwddm_job_last_fail{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{execution_chain}}"
    },
    {
     "expr": "iwddm_job_last_success{tenant=~\"$Tenant\"} unless iwddm_job_last_fail{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{execution_chain}}"
    },
    {
     "expr": "(iwddm_job_last_fail{tenant=~\"$Tenant\"} unless iwddm_job_last_success{tenant=~\"$Tenant\"}) - time()",
     "legendFormat": "{{tenant}} - {{execution_chain}}"
    }
   ]
  },
  {
   "title": "Job schedule",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "iwddm_job_last_start{tenant=~\"$Tenant\"} * 1000"
    },
    {
     "expr": "iwddm_job_last_fail{tenant=~\"$Tenant\"} * 1000 "
    },
    {
     "expr": "iwddm_job_last_success{tenant=~\"$Tenant\"} * 1000"
    },
    {
     "expr": "(iwddm_job_last_fail{tenant=~\"$Tenant\"} - iwddm_job_last_start{tenant=~\"$Tenant\"} > 0) or (iwddm_job_last_success{tenant=~\"$Tenant\"} - iwddm_job_last_start{tenant=~\"$Tenant\"} > 0)"
    }
   ]
  },
  { "title": "Tenant - $Tenant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "Tenant" },
  {
   "title": "Job status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "iwddm_job_last_success{tenant=~\"$Tenant\"} - iwddm_job_last_fail{tenant=~\"$Tenant\"}",
     "legendFormat": "{{execution_chain}}"
    },
    {
     "expr": "iwddm_job_last_success{tenant=~\"$Tenant\"} unless iwddm_job_last_fail{tenant=~\"$Tenant\"}",
     "legendFormat": "{{execution_chain}}"
    },
    {
     "expr": "(iwddm_job_last_fail{tenant=~\"$Tenant\"} unless iwddm_job_last_success{tenant=~\"$Tenant\"}) - time()",
     "legendFormat": "{{execution_chain}}"
    }
   ]
  },
  {
   "title": "Job status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "iwddm_job_last_start{tenant=~\"$Tenant\"} * 1000"
    },
    {
     "expr": "iwddm_job_last_fail{tenant=~\"$Tenant\"} * 1000 "
    },
    {
     "expr": "iwddm_job_last_success{tenant=~\"$Tenant\"} * 1000"
    }
   ]
  },
  {
   "title": "Jobs in Active state",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "iwddm_job_active{tenant=~\"$Tenant\"}",
     "legendFormat": "execution_chain: {{execution_chain}}"
    }
   ]
  }
 ]
}