{
 "title": "Database stats",
 "tags": [ "iwddm" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Tenant",
    "query": "label_values(iwddm_job_active,tenant)"
   }
  ]
 },
 "panels": [
  { "title": "Tenant $Tenant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Tenant" },
  {
   "title": "Database estimated stats",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "iwddm_database_stats_rows{tenant=~\"$Tenant\"} * 1"
    },
    {
     "expr": "iwddm_database_stats_size{tenant=~\"$Tenant\"} * 1"
    }
   ]
  },
  {
   "title": "Database general stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "Number of tasks" },
    {
     "expr": "iwddm_etl_stats_general_events{tenant=~\"$Tenant\"}",
     "legendFormat": "Number of events in run"
    },
    {
     "expr": "iwddm_etl_stats_general_pending{tenant=~\"$Tenant\"}",
     "legendFormat": "Number of pending events"
    },
    {
     "expr": "iwddm_etl_stats_general_avg_events{tenant=~\"$Tenant\"}",
     "legendFormat": "Avg number of events per task"
    },
    {
     "expr": "iwddm_etl_stats_general_max_events{tenant=~\"$Tenant\"}",
     "legendFormat": "Maximum number of events per task"
    }
   ]
  },
  {
   "title": "Number of new keys that added in a current run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iwddm_etl_stats_dimensions_new{tenant=~\"$Tenant\"} * 1",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Total number of keys in a current run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iwddm_etl_stats_dimensions_distinct{tenant=~\"$Tenant\"} * 1",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Number of keys which should be loaded or added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iwddm_etl_stats_dimensions_not_cached{tenant=~\"$Tenant\"} * 1",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Number of keys which are loaded from the database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iwddm_etl_stats_dimensions_cache_missed{tenant=~\"$Tenant\"} * 1",
     "legendFormat": "{{dimension}}"
    }
   ]
  }
 ]
}