{
 "title": "Interaction Server",
 "tags": [ "IXN" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Tenant",
    "label": "Tenants",
    "query": "label_values(up{service=\"ixn\", container=\"ixn-server\"}, tenant)"
   },
   {
    "name": "ClientType",
    "query": "Proxy,Media server,Agent application,Reporting engine"
   }
  ]
 },
 "panels": [
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Is Up",
   "type": "flant-statusmap-panel",
   "description": "The status of service monitoring: is it up or not",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{namespace=\"ixn\", tenant=~\"$Tenant\", container=\"ixn-server\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection to Config Server",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ixn_health_info_config_server_connected{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "IXN Run Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ixn_health_info_run_mode{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Switch to Primary Date/Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(tenant) (ixn_health_info_switch_to_primary_time{tenant=~\"$Tenant\"}*1000)",
     "legendFormat": "{{tenant}}"
    },
    {
     "expr": "(time() - (max by(tenant) (ixn_health_info_switch_to_primary_time{tenant=~\"$Tenant\"})))"
    }
   ]
  },
  { "title": "Client Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Current Clients",
   "type": "graph",
   "description": "Number of currently connected clients",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_clients{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Current Routers",
   "type": "graph",
   "description": "Number of currently connected routers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_routers{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Current $ClientType Clients",
   "type": "graph",
   "description": "Number of currently connected clients of type $ClientType",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "repeat": "ClientType",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_client_count{tenant=~\"$Tenant\", client_type_name=\"$ClientType\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Network Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Pending Network Requests",
   "type": "graph",
   "description": "The current number of the pending network requests in the wait queue. This number includes connects and disconnects",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_request_queue_size{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Request Receiving Rate",
   "type": "graph",
   "description": "The rate of the request receiving",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_total_requests_received{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total Received Requests",
   "type": "graph",
   "description": "The total number of the received requests",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_total_requests_received{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Request Wait Time",
   "type": "graph",
   "description": "The wait time of the last handled network request in the wait queue",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_request_queue_wait{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Request Handling Rate",
   "type": "graph",
   "description": "The rate of the request handling",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_total_requests_handled{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total Handled Requests",
   "type": "graph",
   "description": "The total number of the handled requests",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_total_requests_handled{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Router Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Total Submitted",
   "type": "graph",
   "description": "Number of the interactions submitted to router",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_router_total_submitted{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{router_name}}"
    }
   ]
  },
  {
   "title": "Submit Rate",
   "type": "graph",
   "description": "Rate of the submitting interactions to router",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_router_total_submitted{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}} - {{router_name}}"
    }
   ]
  },
  {
   "title": "Loaded Strategies",
   "type": "graph",
   "description": "Number of the strategies currently loaded by router",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant, router_name) (ixn_health_info_router_strategy_load_count{tenant=~\"$Tenant\"})",
     "legendFormat": "{{tenant}} - {{router_name}}"
    }
   ]
  },
  {
   "title": "Current Capacity",
   "type": "graph",
   "description": "Number of the interactions which can be additionally submitted to router",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_router_current_capacity{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{router_name}}"
    }
   ]
  },
  {
   "title": "Currently Submitted",
   "type": "graph",
   "description": "Number of the interactions currently submitted to router",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_router_currently_submitted{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{router_name}}"
    }
   ]
  },
  {
   "title": "Total Strategies",
   "type": "graph",
   "description": "Total number of the configured strategies",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_strategies{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Max Capacity",
   "type": "graph",
   "description": "Maximum number of the interactions which can be submitted to router",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_router_max_submitted{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{router_name}}"
    }
   ]
  },
  {
   "title": "NonEmpty Views",
   "type": "graph",
   "description": "Total number of the views with the interactions",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (tenant) (ixn_health_info_view_have_interactions{tenant=~\"$Tenant\"} > 0)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Frozen Views",
   "type": "graph",
   "description": "Current number of the frozen views",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (tenant) (ixn_health_info_view_frozen{tenant=~\"$Tenant\"} > 0)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total Views",
   "type": "graph",
   "description": "Total number of the configured views",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_views{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Current Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Current DB Requests",
   "type": "graph",
   "description": "Number of current DB requests",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_database_requests{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "DB Request Rate",
   "type": "graph",
   "description": "Rate of the DB requests",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 83 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_total_database_requests{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total DB Requests",
   "type": "graph",
   "description": "Number of total DB requests",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_total_database_requests{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Current DB Connections",
   "type": "graph",
   "description": "Number of current DB connections",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_database_connections{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "High DB Stack Size (10m)",
   "type": "graph",
   "description": "Minimum nonzero number of current DB requests during 10 minutes interval",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min_over_time(ixn_health_info_current_database_requests{tenant=~\"$Tenant\"}[10m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total DB Deadlocks",
   "type": "graph",
   "description": "Number of total DB deadlocks",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_total_database_deadlocks{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Duration of DB Init Process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "max by(tenant) ((ixn_health_info_db_init_end_time > 0 OR timestamp(ixn_health_info_db_init_start_time)) - (ixn_health_info_db_init_start_time > 0))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Historical Duration of DB Init Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "expr": "max by(tenant) ( 1/(ixn_health_info_db_init_in_progress{tenant=~\"$Tenant\"}==bool 0) * (ixn_health_info_db_init_end_time-ixn_health_info_db_init_start_time) )",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Internal Task Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Current Internal Tasks",
   "type": "graph",
   "description": "Number of current internal tasks",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_current_tasks{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Internal Task Rate",
   "type": "graph",
   "description": "Rate of the internal tasks",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 108 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_total_tasks{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total Internal Tasks",
   "type": "graph",
   "description": "Number of current total tasks since start",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_total_tasks{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "The Bottom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 117 },
   "content": "\n<h1 style=\"text-align: center;\">The Bottom</h1>"
  }
 ]
}