{
 "title": "Interaction Server Event Loggers",
 "tags": [ "IXN" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Tenant",
    "label": "Tenants",
    "query": "label_values(up{service=\"ixn\", container=\"ixn-server\"}, tenant)"
   },
   {
    "name": "Logger",
    "query": "label_values(ixn_health_info_event_logger_current_queue_size, event_logger_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current  Event Loggers",
     "type": "graph",
     "description": "Number of the currently configured event loggers",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_current_loggers{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Provided to All Loggers",
     "type": "graph",
     "description": "Number of the events provided to all event loggers",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_total_loggers_events_received{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Processed by All Loggers",
     "type": "graph",
     "description": "Number of the events processed by all event loggers",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_total_loggers_events_commited{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Discarded By All Loggers",
     "type": "graph",
     "description": "Number of the events discarded by an overflow of all event loggers",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ixn_health_info_total_loggers_events_discarded_due_to_overflow{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    }
   ]
  },
  { "title": "$Logger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "Logger" },
  {
   "title": "Provided Events",
   "type": "graph",
   "description": "Number of the events provided to the event logger",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_event_logger_total_events_received{tenant=~\"$Tenant\", event_logger_name=\"$Logger\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Providing Rate",
   "type": "graph",
   "description": "Rate of the providing events to the event logger",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_event_logger_total_events_received{tenant=~\"$Tenant\", event_logger_name=\"$Logger\"}[5m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Filtered Out Events",
   "type": "graph",
   "description": "Number of the events filtered out from event logger",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_event_logger_total_events_filtered_out_by_id{tenant=~\"$Tenant\", event_logger_name=\"$Logger\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Processed Events",
   "type": "graph",
   "description": "Number of the events processed by the event logger",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_event_logger_total_events_commited{tenant=~\"$Tenant\", event_logger_name=\"$Logger\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Processing Rate",
   "type": "graph",
   "description": "Rate of the processing events by the event logger",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(ixn_health_info_event_logger_total_events_commited{tenant=~\"$Tenant\", event_logger_name=\"$Logger\"}[5m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Discarded Events",
   "type": "graph",
   "description": "Number of the events discarded due to an overflow of the event logger queue",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixn_health_info_event_logger_total_events_discarded_due_to_overflow{tenant=~\"$Tenant\", event_logger_name=\"$Logger\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "The Bottom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "\n<h1 style=\"text-align: center;\">The Bottom</h1>"
  }
 ]
}