{
 "title": "Interaction Server Node",
 "tags": [ "IXN" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Tenant",
    "query": "label_values(up{service=\"ixn\", tenant!=\"shared\"}, tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Is Up",
   "type": "flant-statusmap-panel",
   "description": "The status of service monitoring: is it up or not",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{namespace=\"ixn\", tenant=~\"$Tenant\", container=\"ixn-node\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Routing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Pulled",
   "type": "graph",
   "description": "Total number of the interactions pulled for the specific strategy",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_interactions_pulled_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Pull Rate",
   "type": "graph",
   "description": "The per-second average rate of increase of the total number of the interactions pulled for the specific strategy",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_interactions_pulled_total{tenant=~\"$Tenant\"}[1m])",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Routing Sessions",
   "type": "graph",
   "description": "The current number of the routing sessions in routing",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_routing_sessions_in_routing {tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total Terminal Routing Instructions",
   "type": "graph",
   "description": "The total number of the routing instructions processed",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_routing_instructions_received_total{tenant=~\"$Tenant\", type=\"terminal\"}",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Terminal Routing Instruction Rate",
   "type": "graph",
   "description": "The total number of the routing instructions processed",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_routing_instructions_received_total{tenant=~\"$Tenant\", type='terminal'}[1m])",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Interactions Placed Back Total",
   "type": "graph",
   "description": "Total number of times interaction was placed back in queue by reason. List of reasons:\n- StrategyRequest - Strategy requested placing interaction back into queue explicitly. Set by ORS.\n- Implicit - Strategy did nothing and ORS places interaction back cause there are no instructions for it. Set by ORS.\n- Error - ORS places interaction back into queue due to some error regardless of the error source be it strategy itself or any other reason. Set by ORS.\n- InternalError - IXN Node failed to send interaction to ORS and places it back into queue.\n- Unknown - Reason was not specified.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_interactions_placed_back_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{reason}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total Non-Terminal Routing Instructions",
   "type": "graph",
   "description": "The total number of the routing instructions processed",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_routing_instructions_received_total{tenant=~\"$Tenant\", type=\"non-terminal\"}",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Non-Terminal Routing Instruction Rate",
   "type": "graph",
   "description": "The total number of the routing instructions processed",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_routing_instructions_received_total{tenant=~\"$Tenant\", type='non-terminal'}[1m])",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Age of Last Fetched Configuration",
   "type": "table",
   "description": "How long ago routing configuration was fetched successfully.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "(time() - ixnnode_last_fetched_configuration_timestamp{tenant=~\"$Tenant\"})"
    }
   ]
  },
  {
   "title": "Number of Configured Strategies",
   "type": "graph",
   "description": "Number of the strategies read from configuration for which interactions should be being pulled.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_configured_strategies_current{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Running Strategies",
   "type": "graph",
   "description": "Number of the strategies for which interactions are being pulled currently.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_running_strategies_current{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total Configuration Fetch Errors",
   "type": "graph",
   "description": "Total number of configuration fetching errors.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_configuration_fetch_errors_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  { "title": "Routing Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Pulling Interactions for Startegies",
   "type": "flant-statusmap-panel",
   "description": "The status of pulling interactions for strategy. Pulling is cycling process and it may get stuck for some causes, thus routing for corresponding strategies fails.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "# As increase and rate are extrapolated to cover the full time range, \"AND ixnnode_pull_request_total\" is added not to have values within 5m after a service has been stopped.\nfloor(\n  (sum by (tenant)((increase(ixnnode_pull_request_total[5m]) AND ixnnode_pull_request_total) > bool 0) \n    / count by (tenant)(ixnnode_pull_request_total)\n    - 0.001\n  ) / 0.998\n)\nOR min by (tenant)(((up{servicename=\"ixn\", container=\"ixn-node\"} > 0) > bool 1) - 1)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Processing of Instructions Received from ORS",
   "type": "flant-statusmap-panel",
   "description": "The size of the queue of  routing instructions waiting for completion processing is under limit.\nWhen the queue size reaches the limit defined in IXN Node, reading of  routing instructions stops.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "min by (tenant)(\r\n  (ixnnode_instructions_processing_queue_concurrency_limit - \r\n    sum without(type)(ixnnode_instructions_processing_queue_size))\r\n  +\r\n  increase(ixnnode_all_instructions_received_total[1m])\r\n\r\n) > bool 0\nOR min by (tenant)((up{servicename=\"ixn\", container=\"ixn-node\"} > 0) > bool 1)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Pull Requests Total",
   "type": "graph",
   "description": "Number of RequestPull successfully completed by InteractionServer.\nA metric increasing at a constant rate means a routing cycle for a specific strategy is working fine.\nPossible issues:\n - IxN client can't send a request or the request timeout has expired - routing cycle stops until reconnect to IxN Server\n - IxN server returns something wrong - routing cycle waits 10 secs and continues\n - sending an interaction to ORS failed - routing cycle got stuck (RqClient issue) or waits 10 secs after an exception and continuous",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_pull_request_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Pull Requests Rate",
   "type": "graph",
   "description": "Number of RequestPull successfully completed by InteractionServer.\nA metric increasing at a constant rate means a routing cycle for a specific strategy is working fine.\nPossible issues:\n - IxN client can't send a request or the request timeout has expired - routing cycle stops until reconnect to IxN Server\n - IxN server returns something wrong - routing cycle waits 10 secs and continues\n - sending an interaction to ORS failed - routing cycle got stuck (RqClient issue) or waits 10 secs after an exception and continuous",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_pull_request_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Difference between number of interactions pulled and route requests sent",
   "type": "graph",
   "description": "Difference between number of interactions pulled and route requests sent.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ixnnode_interactions_pulled_total{tenant=~\"$Tenant\"} - ixnnode_route_request_sent_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of route requests failed to send to ORS",
   "type": "graph",
   "description": "Number of route requests failed to send to ORS.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_route_request_failed_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{strategy}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Difference between number of unsolicited notifications received and sent",
   "type": "graph",
   "description": "Difference between  the number of unsolicited notifications received and sent.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_unsolicited_notifications_total{tenant=~\"$Tenant\"} - ixnnode_unsolicited_notifications_sent_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of routing instructions waiting for processing",
   "type": "graph",
   "description": "Number of routing instructions waiting for processing",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_instructions_processing_queue_size{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Routing Instruction Processed by IXN Server Current",
   "type": "graph",
   "description": "Current number of routing instructions being processed by IXN Server.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_instructions_processed_by_ixn_current{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Unsolicited Notifications Failed to Send to ORS Total",
   "type": "graph",
   "description": "Total number of unsolicited events failed to send to ORS.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_unsolicited_notifications_failed_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  { "title": "Unsolicited notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Total Unsolicited Notifications",
   "type": "graph",
   "description": "The total number of the unsolicited notifications",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ixnnode_unsolicited_notifications_total{tenant=~\"$Tenant\"}",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Unsolicited Notification Rate",
   "type": "graph",
   "description": "The total number of the unsolicited notifications",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ixnnode_unsolicited_notifications_total{tenant=~\"$Tenant\"}[5m])",
     "legendFormat": "{{tenant}} - {{instance}}"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Server Errors",
     "type": "graph",
     "description": "The total number of all API requests with server error response",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixnnode_server_error_total{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Total Client Errors",
     "type": "graph",
     "description": "The total number of all API requests with client error response",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixnnode_client_error_total{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Total Errors",
     "type": "graph",
     "description": "The total number of all API requests with error response",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixnnode_errors_total{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inbound requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "graph",
     "description": "The total number of all API requests received",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixnnode_request_total{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "graph",
     "description": "The per-second average rate of increase of the total number of all API requests received",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(ixnnode_request_total{tenant=~\"$Tenant\"}[1m])",
       "legendFormat": "{{tenant}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Total Successful Requests",
     "type": "graph",
     "description": "The total number of all API requests with success response",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ixnnode_success_total{tenant=~\"$Tenant\"}",
       "legendFormat": "{{tenant}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}