{
 "title": "WhatsApp",
 "tags": [ "Nexus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cloud", "query": { "query": "up{}" } },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "up{cloud=\"${cloud}\"}"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(up{environment=~\"${environment}\",cloud=~\"${cloud}\",service=\"nexus\"},location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Webhooks Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(hubpp_webhook_received_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m]))",
     "legendFormat": "Webhook Total"
    }
   ]
  },
  {
   "title": "WhatsApp Sent Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(hubpp_public_send_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m]))",
     "legendFormat": "WhatsApp Sent"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(hubpp_errors_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m]))",
     "legendFormat": "Total errors"
    }
   ]
  },
  {
   "title": "WhatsApp Send Status codes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (statusCode) (increase(hubpp_public_send_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m]))",
     "legendFormat": "{{ statusCode }}"
    }
   ]
  },
  {
   "title": "Received webhook rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (channelId) (increase(hubpp_webhook_received_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m]))",
     "legendFormat": "channel: {{ channelId }}"
    }
   ]
  },
  {
   "title": "WhatsApp Send",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (channelId, statusCode) (increase(hubpp_public_send_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m]))",
     "legendFormat": "{{statusCode}}::{{channelId}}"
    }
   ]
  },
  {
   "title": "Average whatsapp send duration ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubpp_whatsapp_send_duration_sum{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])) by (url, statusCode) / sum(rate(hubpp_whatsapp_send_duration_count{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])) by (url, statusCode)",
     "legendFormat": "{{ statusCode }} :: {{url}}"
    }
   ]
  },
  {
   "title": "Hubpp error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hubpp_errors_total{cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Webhook Undefined Secret",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(hubpp_webhook_channel_undefined_secret_total{channelType=\"whatsapp\", channelProvider=\"PEC\", cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Webhook Undefined Signature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(hubpp_webhook_undefined_signature_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Webhook Invalid Signature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(hubpp_webhook_invalid_signature_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Webhook Unknown Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(hubpp_webhook_unknown_channel_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Webhook errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(hubpp_webhook_with_error_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Webhook Errors Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hubpp_webhook_with_error_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[5m])",
     "legendFormat": "{{channelId}} code:{{errorCode}} status:{{httpStatus}}"
    }
   ]
  },
  {
   "title": "Webhook Undefined Secret:: Top 10 Channel ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10,sum by (channelId)(increase(hubpp_webhook_channel_undefined_secret_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]) > 0))",
     "legendFormat": "{{channelId}}"
    }
   ]
  },
  {
   "title": "Webhook Undefined Signature :: Top 10 Channel ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "topk(10,sum by (channelId)(increase(hubpp_webhook_undefined_signature_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]) > 0))",
     "legendFormat": "{{channelId}}"
    }
   ]
  },
  {
   "title": "Webhook Invalid Signature :: Top 10 Channel ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "topk(10,sum by (channelId)(increase(hubpp_webhook_invalid_signature_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]) > 0))",
     "legendFormat": "{{channelId}}"
    }
   ]
  },
  {
   "title": "Webhook Unknown Сhannels :: Top 10 Channel ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "topk(10,sum by (channelId)(increase(hubpp_webhook_unknown_channel_total{channelType=\"whatsapp\", channelProvider=\"PEC\",cloud=~\"$cloud\",environment=~\"$environment\",location=~\"$location\"}[$__range]) > 0))",
     "legendFormat": "{{channelId}}"
    }
   ]
  }
 ]
}