{
 "title": "NexusApi",
 "tags": [ "Nexus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cloud", "query": { "query": "up{}" } },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "up{cloud=\"${cloud}\"}"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(up{environment=~\"${environment}\",cloud=~\"${cloud}\",service=\"nexus\"},location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nexus_api_request_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[1m]))",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( sum(increase(nexus_errors_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[$__range])) / sum(increase(nexus_request_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[$__range])) )",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n sum(irate(nexus_api_request_duration_milliseconds_bucket{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\",le=\"100\",code=~\"^2..$\"}[1m]))\n +\n sum(irate(nexus_api_request_duration_milliseconds_bucket{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\",le=\"500\",code=~\"^2..$\"}[1m]))\n) / 2 / sum(irate(nexus_api_request_duration_milliseconds_count{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[1m]))",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " (max(irate(nexus_process_cpu_seconds_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[5m])) * 100)",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Total Memory: RSS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nexus_process_resident_memory_bytes{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"})",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Total Memory: Heap Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nexus_nodejs_heap_size_used_bytes{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"})",
     "legendFormat": "Total ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Nexus CPU Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(nexus_process_cpu_seconds_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[5m]))*100",
     "legendFormat": "{{ instance }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Nexus Memory usage, Mb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (nexus_process_resident_memory_bytes{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"})",
     "legendFormat": "RSS ({{instance}}) ${cloud}-${environment}-${location}"
    },
    {
     "expr": "avg by (instance) (nexus_nodejs_heap_size_used_bytes{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"} )",
     "legendFormat": "Heap Used ({{instance}}) ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Node.js Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nexus_nodejs_eventloop_lag_seconds{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}",
     "legendFormat": "{{ instance }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nexus_process_open_fds{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}",
     "legendFormat": "{{ instance }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nexus_nodejs_active_handles_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}",
     "legendFormat": "{{ instance }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Active Nodejs Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nexus_nodejs_active_requests_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}",
     "legendFormat": "{{ instance }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(nexus_errors_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[5m])) / sum(rate(nexus_request_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[5m])) )",
     "legendFormat": " ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Apdex Score: target 100ms, tolerated: 500ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n sum(irate(nexus_api_request_duration_milliseconds_bucket{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\",le=\"100\",code=~\"^2..$\"}[1m]))\n+\n sum(irate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",le=\"500\",code=~\"^2..$\"}[1m]))\n) / 2 / sum(irate(nexus_api_request_duration_milliseconds_count{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[1m]))",
     "legendFormat": "Apdex score ${cloud}-${environment}-${location}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nexus_api_request_duration_milliseconds_count{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",path=~\"/nexus.*\"}[1m])) by (path, method) * 60",
     "legendFormat": "{{method}} {{path}} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nexus_api_request_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[1m]))",
     "legendFormat": "Request Rate ${cloud}-${environment}-${location}"
    },
    {
     "expr": "sum (rate(nexus_api_request_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",code=~\"^5 ..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate ${cloud}-${environment}-${location}"
    },
    {
     "expr": "sum (rate(nexus_api_request_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",code=~\"^4..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate ${cloud}-${environment}-${location}"
    },
    {
     "expr": "sum (rate(nexus_api_request_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",code=~\"^2..$\"}[1m]))",
     "legendFormat": "2XX Success Rate ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nexus_api_request_duration_milliseconds_sum{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[1m])) by (code) / sum(rate(nexus_api_request_duration_milliseconds_count{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[1m])) by (code)",
     "legendFormat": "Response code: {{ code }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (irate(nexus_api_request_total{environment=\"$environment\",location=\"$location\",cloud=\"$cloud\"}[1m])) ",
     "legendFormat": "{{ method }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",le=\"10\"}[1m])) / sum(irate(nexus_api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 10ms (%) ${cloud}-${environment}-${location}"
    },
    {
     "expr": "( sum(irate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",le=\"50\"}[1m])) / sum(irate(nexus_api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 50ms (%) ${cloud}-${environment}-${location}"
    },
    {
     "expr": "( sum(irate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",le=\"100\"}[1m])) / sum(irate(nexus_api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%) ${cloud}-${environment}-${location}"
    },
    {
     "expr": "( sum(irate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",le=\"500\"}[1m])) / sum(irate(nexus_api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%) ${cloud}-${environment}-${location}"
    },
    {
     "expr": "( sum(irate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",le=\"1000\"}[1m])) / sum(irate(nexus_api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 1000ms (%) ${cloud}-${environment}-${location}"
    },
    {
     "expr": "( sum(irate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",le=\"5000\"}[1m])) / sum(irate(nexus_api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 5000ms (%) ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Top 3 API calls rate (by path)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(nexus_api_request_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",path!~\"/health.*\"}[5m])) by (path))",
     "legendFormat": "{{ path }} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( by path)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(nexus_api_request_total{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",code!=\"200\"}[5m])) by (path, code))",
     "legendFormat": "{{ code }}::{{path}} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",path=~\"/nexus.*\"}[1m])) by (le, instance, path, method))",
     "legendFormat": "{{method}} {{path}} ${cloud}-${environment}-${location}"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nexus_api_request_duration_milliseconds_bucket{cloud=~\"${cloud}\",environment=~\"${environment}\",location=~\"${location}\",path=~\"/nexus.*\"}[1m])) by (le, instance, path, method))",
     "legendFormat": "{{instance}} - {{method}} {{path}} ${cloud}-${environment}-${location}"
    }
   ]
  }
 ]
}