{
 "title": "DCU / Containers",
 "tags": [
  "pulse",
  "dcu",
  "collector",
  "statserver"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "dcu" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-[0-9]+-.*\"}, pod)"
   },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-($Tenant)-.*\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-($Tenant)-.*\"}, pod)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"$Pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}[5m]))",
     "legendFormat": "{{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, container) (container_memory_working_set_bytes{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"})",
     "legendFormat": "{{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "CPU Usage (Limits), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}[5m])) /\nsum by(pod, container) (kube_pod_container_resource_limits{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"cpu\",unit=\"core\"}) *\n100",
     "legendFormat": "{{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "Memory Usage (Limits), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, container) (container_memory_working_set_bytes{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}) /\nsum by(pod, container) (kube_pod_container_resource_limits{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"memory\",unit=\"byte\"}) *\n100",
     "legendFormat": "{{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "CPU Usage (Requests), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}[5m])) /\nsum by(pod, container) (kube_pod_container_resource_requests{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"cpu\",unit=\"core\"}) *\n100",
     "legendFormat": "{{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "Memory Usage (Requests), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, container) (container_memory_working_set_bytes{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}) /\nsum by(pod, container) (kube_pod_container_resource_requests{namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"memory\",unit=\"byte\"}) *\n100",
     "legendFormat": "{{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  }
 ]
}