{
 "title": "DCU / Collectors",
 "tags": [
  "pulse",
  "dcu",
  "collector"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "dcu" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-[0-9]+-.*\"}, pod)"
   },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-($Tenant)-.*\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-($Tenant)-.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod,connection) (pulse_collector_connection_status{namespace=\"$Namespace\",pod=~\"$Pod\"}) > bool 0",
     "legendFormat": "{{`{{pod}}`}} -> {{`{{connection}}`}}"
    }
   ]
  },
  {
   "title": "Writing Snapshot Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (pulse_collector_snapshot_writing_status{namespace=\"$Namespace\",pod=~\"$Pod\"}) > bool 0",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Active Layouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (pulse_collector_active_layouts_count{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Pending Layout Status Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (pulse_collector_pending_layout_status_changes_count{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Total Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (pulse_collector_statistics_total_count{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Open Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (pulse_collector_statistics_opened_count{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Max Statistics Values Delay, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (pulse_collector_max_statistic_value_delay{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Failed Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (pulse_collector_statistics_failed_count{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}