{
 "title": "LDS / Servers",
 "tags": [
  "pulse",
  "lds"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "lds,lds-vq" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-[0-9]+-.*\"}, pod)"
   },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-($Chart)-($Tenant)-.*\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-($Tenant)-.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Senders",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod,sender) (pulse_lds_sender_connected_seconds{namespace=\"$Namespace\",pod=~\"$Pod\"}) > bool 0",
     "legendFormat": "{{`{{pod}}`}} -> {{`{{sender}}`}}"
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (pulse_lds_receivers_number{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Senders: Registered DNs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_sender_registered_dns_number{namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{sender}}`}}"
    }
   ]
  },
  {
   "title": "Receivers: Registered DNs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_receiver_registered_dns_number{namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{receiver}}`}}"
    }
   ]
  },
  {
   "title": "Senders: Registration Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_sender_registration_errors_number{namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{sender}}`}}"
    }
   ]
  },
  {
   "title": "Receivers: Registration Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_receiver_registration_errors_number{namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{receiver}}`}}"
    }
   ]
  },
  {
   "title": "Senders: Request Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_sender_request_queue_length{namespace=\"$Namespace\", pod=~\"$Pod\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{sender}}`}}"
    }
   ]
  }
 ]
}