{
 "title": "Permissions / Containers",
 "tags": [
  "pulse",
  "permissions"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Cloud", "label": "Cloud", "query": { "query": "label_values(up{},cloud)" } },
   {
    "name": "Environment",
    "label": "Environment",
    "query": {
     "query": "label_values(up{cloud=~\"$Cloud\"},environment)"
    }
   },
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "label_values(up{cloud=~\"$Cloud\",environment=~\"$Environment\"},location)"
    }
   },
   { "name": "Namespace", "label": "Namespace", "query": "pulse" },
   { "name": "Chart", "label": "Chart", "query": "permissions" },
   {
    "name": "Tenant",
    "query": {
     "query": "label_values(kube_pod_container_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\".*-($Chart)-[0-9]+-.*\"}, pod)"
    }
   },
   {
    "name": "Release",
    "label": "Release",
    "query": {
     "query": "label_values(kube_pod_container_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\".*-($Chart)-($Tenant)-.*\"}, pod)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\"($Release)-($Tenant)-.*\"}, pod)"
    }
   },
   {
    "name": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\", pod=~\"$Pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod, container) (rate(container_cpu_usage_seconds_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}[5m]))",
     "legendFormat": "{{container}} (Pod: {{pod}}@{{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod, container) (container_memory_working_set_bytes{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"})",
     "legendFormat": "{{container}} (Pod: {{pod}}@{{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "CPU Usage (Limits), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod, container) (rate(container_cpu_usage_seconds_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}[5m])) /\nsum by(cloud,environment,location,pod, container) (kube_pod_container_resource_limits{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"cpu\",unit=\"core\"}) *\n100",
     "legendFormat": "{{container}} (Pod: {{pod}}@{{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "Memory Usage (Limits), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod, container) (container_memory_working_set_bytes{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}) /\nsum by(cloud,environment,location,pod, container) (kube_pod_container_resource_limits{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"memory\",unit=\"byte\"}) *\n100",
     "legendFormat": "{{container}} (Pod: {{pod}}@{{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "CPU Usage (Requests), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod, container) (rate(container_cpu_usage_seconds_total{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}[5m])) /\nsum by(cloud,environment,location,pod, container) (kube_pod_container_resource_requests{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"cpu\",unit=\"core\"}) *\n100",
     "legendFormat": "{{container}} (Pod: {{pod}}@{{cloud}}-{{environment}}-{{location}})"
    }
   ]
  },
  {
   "title": "Memory Usage (Requests), %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(cloud,environment,location,pod, container) (container_memory_working_set_bytes{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\"}) /\nsum by(cloud,environment,location,pod, container) (kube_pod_container_resource_requests{cloud=~\"$Cloud\",environment=~\"$Environment\",location=~\"$Location\",namespace=\"$Namespace\",pod=~\"$Pod\",container=~\"$Container\",resource=\"memory\",unit=\"byte\"}) *\n100",
     "legendFormat": "{{container}} (Pod: {{pod}}@{{cloud}}-{{environment}}-{{location}})"
    }
   ]
  }
 ]
}