{
 "title": "Backend / Pods",
 "tags": [
  "pulse",
  "backend"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "pulse" },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"^(.*-)?($Chart)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"$Pod\"}, container)"
   },
   {
    "name": "Deployment",
    "label": "Deployment",
    "query": "label_values(kube_pod_info{namespace=\"$Namespace\", pod=~\"$Pod\"}, created_by_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Failed\"}) + \n2 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Pending\"}) + \n3 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Running\"}) + \n4 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\",phase=\"Succeeded\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Running Instances, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_available{namespace=\"$Namespace\",deployment=~\"$Deployment\"}) /\nsum by(deployment) (kube_deployment_status_replicas{namespace=\"$Namespace\",deployment=~\"$Deployment\"}) * 100",
     "legendFormat": "{{`{{deployment}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",pod=~\"$Pod\"}[5m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$Namespace\",container!=\"POD\",container!=\"\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "RX: {{`{{pod}}`}}"
    },
    {
     "expr": "sort_desc(sum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"$Namespace\", pod=~\"$Pod\"}[5m])))",
     "legendFormat": "TX: {{`{{pod}}`}}"
    }
   ]
  }
 ]
}