{
 "title": "Pulse Overall Health",
 "tags": [ "pulse" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "BackendChart", "label": "BackendChart", "query": "pulse" },
   {
    "name": "BackendRelease",
    "label": "BackendRelease",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"^(.*-)?($BackendChart)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "BackendPod",
    "label": "BackendPod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($BackendRelease)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "BackendDeployment",
    "label": "BackendDeployment",
    "query": "label_values(kube_pod_info{namespace=\"$Namespace\", pod=~\"$BackendPod\"}, created_by_name)"
   },
   { "name": "PermissionsChart", "label": "PermissionsChart", "query": "permissions" },
   { "name": "DcuChart", "label": "DcuChart", "query": "dcu" },
   { "name": "LdsChart", "label": "LdsChart", "query": "lds,lds-vq" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\".*-(($DcuChart|$LdsChart)-[0-9]+-[0-9]+|($PermissionsChart)-[0-9]+-[^-]+-[^-]{5})$\"}, pod)"
   },
   {
    "name": "PermissionsRelease",
    "label": "PermissionsRelease",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"^.*-($PermissionsChart)-($Tenant)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "DcuRelease",
    "label": "DcuRelease",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"^.*-($DcuChart)-($Tenant)-[0-9]+$\"}, pod)"
   },
   {
    "name": "LdsRelease",
    "label": "LdsRelease",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"^.*-($LdsChart)-($Tenant)-[0-9]+$\"}, pod)"
   },
   {
    "name": "PermissionsPod",
    "label": "PermissionsPod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($PermissionsRelease)-($Tenant)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "DcuPod",
    "label": "DcuPod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($DcuRelease)-($Tenant)-[0-9]+$\"}, pod)"
   },
   {
    "name": "LdsPod",
    "label": "LdsPod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($LdsRelease)-($Tenant)-[0-9]+$\"}, pod)"
   },
   {
    "name": "PermissionsDeployment",
    "label": "PermissionsDeployment",
    "query": "label_values(kube_pod_info{namespace=\"$Namespace\", pod=~\"$PermissionsPod\"}, created_by_name)"
   },
   {
    "name": "DcuStatefulSet",
    "label": "DcuStatefulSet",
    "query": "label_values(kube_pod_info{namespace=\"$Namespace\", pod=~\"$DcuPod\"}, created_by_name)"
   },
   {
    "name": "LdsStatefulSet",
    "label": "LdsStatefulSet",
    "query": "label_values(kube_pod_info{namespace=\"$Namespace\", pod=~\"$LdsPod\"}, created_by_name)"
   }
  ]
 },
 "panels": [
  { "title": "Shared Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "1 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$BackendPod\",phase=\"Failed\"}) + \n2 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$BackendPod\",phase=\"Pending\"}) + \n3 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$BackendPod\",phase=\"Running\"}) + \n4 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$BackendPod\",phase=\"Succeeded\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Running Instances, %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_available{namespace=\"$Namespace\",deployment=~\"$BackendDeployment\"}) /\nsum by(deployment) (kube_deployment_status_replicas{namespace=\"$Namespace\",deployment=~\"$BackendDeployment\"}) * 100",
     "legendFormat": "{{`{{deployment}}`}}"
    }
   ]
  },
  {
   "title": "Backend Connections Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(pod,connection) (pulse_health_connections_Boolean{namespace=\"$Namespace\",pod=~\"$BackendPod\"}) > bool 0",
     "legendFormat": "{{`{{pod}}`}} -> {{`{{connection}}`}}"
    }
   ]
  },
  {
   "title": "Tenant Services: $Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "Tenant",
   "collapsed": true,
   "panels": [
    {
     "title": "POD Status",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "kube_pod_labels{namespace=\"$Namespace\",pod=~\"$DcuPod\",label_tenant=\"$Tenant\"} * on(pod) (\n1 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$DcuPod\",phase=\"Failed\"}) + \n2 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$DcuPod\",phase=\"Pending\"}) + \n3 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$DcuPod\",phase=\"Running\"}) + \n4 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$DcuPod\",phase=\"Succeeded\"}))",
       "legendFormat": "{{`{{pod}}`}}"
      },
      {
       "expr": "kube_pod_labels{namespace=\"$Namespace\",pod=~\"$LdsPod\",label_tenant=\"$Tenant\"} * on(pod) (\n1 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$LdsPod\",phase=\"Failed\"}) + \n2 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$LdsPod\",phase=\"Pending\"}) + \n3 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$LdsPod\",phase=\"Running\"}) + \n4 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$LdsPod\",phase=\"Succeeded\"}))",
       "legendFormat": "{{`{{pod}}`}}"
      },
      {
       "expr": "kube_pod_labels{namespace=\"$Namespace\",pod=~\"$PermissionsPod\",label_tenant=\"$Tenant\"} * on(pod) (\n1 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$PermissionsPod\",phase=\"Failed\"}) + \n2 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$PermissionsPod\",phase=\"Pending\"}) + \n3 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$PermissionsPod\",phase=\"Running\"}) + \n4 * min by(pod) (kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$PermissionsPod\",phase=\"Succeeded\"}))",
       "legendFormat": "{{`{{pod}}`}}"
      }
     ]
    },
    {
     "title": "Running Instances, %",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_statefulset_labels{namespace=\"$Namespace\",statefulset=~\"$DcuStatefulSet\",label_tenant=\"$Tenant\"} * on(statefulset)\nsum by(statefulset) (kube_statefulset_status_replicas_ready{namespace=\"$Namespace\",statefulset=~\"$DcuStatefulSet\"}) /\nsum by(statefulset) (kube_statefulset_status_replicas{namespace=\"$Namespace\",statefulset=~\"$DcuStatefulSet\"}) * 100",
       "legendFormat": "{{`{{statefulset}}`}}"
      },
      {
       "expr": "kube_statefulset_labels{namespace=\"$Namespace\",statefulset=~\"$LdsStatefulSet\",label_tenant=\"$Tenant\"} * on(statefulset)\nsum by(statefulset) (kube_statefulset_status_replicas_ready{namespace=\"$Namespace\",statefulset=~\"$LdsStatefulSet\"}) /\nsum by(statefulset) (kube_statefulset_status_replicas{namespace=\"$Namespace\",statefulset=~\"$LdsStatefulSet\"}) * 100",
       "legendFormat": "{{`{{statefulset}}`}}"
      },
      {
       "expr": "kube_deployment_labels{namespace=\"$Namespace\",deployment=~\"$PermissionsDeployment\",label_tenant=\"$Tenant\"} * on(deployment)\nsum by(deployment) (kube_deployment_status_replicas_available{namespace=\"$Namespace\",deployment=~\"$PermissionsDeployment\"}) /\nsum by(deployment) (kube_deployment_status_replicas{namespace=\"$Namespace\",deployment=~\"$PermissionsDeployment\"}) * 100",
       "legendFormat": "{{`{{deployment}}`}}"
      }
     ]
    },
    {
     "title": "Writing Snapshot Status",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "kube_pod_labels{namespace=\"$Namespace\",pod=~\"$DcuPod\",label_tenant=\"$Tenant\"} * on(pod)\nsum by(pod) (pulse_collector_snapshot_writing_status{namespace=\"$Namespace\",pod=~\"$DcuPod\"}) > bool 0",
       "legendFormat": "{{`{{pod}}`}}"
      }
     ]
    },
    {
     "title": "Collector Connections Status",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "kube_pod_labels{namespace=\"$Namespace\",pod=~\"$DcuPod\",label_tenant=\"$Tenant\"} * on(pod) group_right()\nsum by(pod,connection) (pulse_collector_connection_status{namespace=\"$Namespace\",pod=~\"$DcuPod\"}) > bool 0",
       "legendFormat": "{{`{{pod}}`}} -> {{`{{connection}}`}}"
      }
     ]
    },
    {
     "title": "LDS Connections Status",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "kube_pod_labels{namespace=\"$Namespace\",pod=~\"$LdsPod\",label_tenant=\"$Tenant\"} * on(pod) group_right()\nsum by(pod,sender) (pulse_lds_sender_connected_seconds{namespace=\"$Namespace\",pod=~\"$LdsPod\"}) > bool 0",
       "legendFormat": "{{`{{pod}}`}} -> {{`{{sender}}`}}"
      }
     ]
    },
    {
     "title": "StatServer Connections Status",
     "type": "state-timeline",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "kube_pod_labels{namespace=\"$Namespace\",pod=~\"$DcuPod\",label_tenant=\"$Tenant\"} * on(pod) group_right()\nsum by(pod,server) (idelta(pulse_statserver_server_connected_seconds{namespace=\"$Namespace\",pod=~\"$DcuPod\"}[1m])) != bool 0",
       "legendFormat": "{{`{{pod}}`}} -> {{`{{server}}`}}"
      }
     ]
    }
   ]
  }
 ]
}