{
 "title": "Backend / Requests",
 "tags": [
  "pulse",
  "backend"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "pulse" },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"^(.*-)?($Chart)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-[^-]+-[^-]{5}$\"}, pod)"
   },
   { "name": "Quantile", "label": "Quantile", "query": "25,50,75,90" }
  ]
 },
 "panels": [
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_server_requests_seconds_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[5m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Max Avg Requests Latency, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (\nrate(http_server_requests_seconds_sum{namespace=\"$Namespace\",pod=~\"$Pod\"}[5m]) /\nrate(http_server_requests_seconds_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[5m])\n)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Max Avg Requests Latency (Quantile: $Quantile%), s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time($Quantile/100,\n  max by(pod) (\n  rate(http_server_requests_seconds_sum{namespace=\"$Namespace\",pod=~\"$Pod\"}[2m]) /\n  rate(http_server_requests_seconds_count{namespace=\"$Namespace\",pod=~\"$Pod\"}[2m])\n  )[10m:2m]\n)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Errors 4xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_server_requests_seconds_count{namespace=\"$Namespace\",pod=~\"$Pod\", status=~\"4.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Errors 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_server_requests_seconds_count{namespace=\"$Namespace\",pod=~\"$Pod\", status=~\"5.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}