{
 "title": "Backend / JVM",
 "tags": [
  "pulse",
  "backend"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "Namespace", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "Chart", "label": "Chart", "query": "pulse" },
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"^(.*-)?($Chart)-[^-]+-[^-]{5}$\"}, pod)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$Namespace\", pod=~\"($Release)-[^-]+-[^-]{5}$\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (jvm_memory_used_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (jvm_memory_used_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) /\nsum by(pod) (jvm_memory_max_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) *\n100",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (jvm_threads_states_threads{namespace=\"$Namespace\",pod=~\"$Pod\", state=\"blocked\"})",
     "legendFormat": "Blocked: {{`{{pod}}`}}"
    },
    {
     "expr": "sum by(pod) (jvm_threads_states_threads{namespace=\"$Namespace\",pod=~\"$Pod\", state=\"waiting\"})",
     "legendFormat": "Waiting: {{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "DB Connections Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (hikaricp_connections_active{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "Active: {{`{{pod}}`}}"
    },
    {
     "expr": "sum by(pod) (hikaricp_connections{namespace=\"$Namespace\",pod=~\"$Pod\"})",
     "legendFormat": "Total: {{`{{pod}}`}}"
    }
   ]
  }
 ]
}