{
 "title": "GIM/GSP/Details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Service",
    "query": "label_values(flink_jobmanager_numRunningJobs,job)"
   }
  ]
 },
 "panels": [
  { "title": "Voice Transformation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Records In/Out",
   "type": "graph",
   "description": "IO in terms of records per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{job=\"$job\",task_name=~\"Xform Voice In.*\"}) by(subtask_index)",
     "legendFormat": "in {{subtask_index}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{job=\"$job\",task_name=~\"Xform Voice In.*\"}) by (subtask_index)",
     "legendFormat": "out {{subtask_index}}"
    }
   ]
  },
  {
   "title": "Back Pressure Status",
   "type": "flant-statusmap-panel",
   "description": "Shows Back Pressure Status for each subtask",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_isBackPressured{job=\"$job\",task_name=~\"Xform Voice I.*\"}) by(subtask_index)/count(flink_taskmanager_job_task_isBackPressured{job=\"$job\",task_name=~\"Xform Voice I.*\"}) by (subtask_index)",
     "legendFormat": "subtask {{subtask_index}}"
    }
   ]
  },
  {
   "title": "Input batch size",
   "type": "heatmap",
   "description": "Input batch size",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_batch_size_le_bucket-flink_taskmanager_job_task_operator_batch_size_le_bucket offset $__interval>=0) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Idle time",
   "type": "graph",
   "description": "The percentage of time the subtask is idle (either has no data to process or it is back pressured)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(floor(flink_taskmanager_job_task_idleTimeMsPerSecond{job=\"$job\",task_name=~\"Xform Voice In.*\"}/100)*100/1000) by (subtask_index) / count(flink_taskmanager_job_task_idleTimeMsPerSecond{job=\"$job\",task_name=~\"Xform Voice In.*\"}) by (subtask_index)",
     "legendFormat": "subtask {{subtask_index}}"
    }
   ]
  },
  {
   "title": "Checkpoint Alignment Time",
   "type": "graph",
   "description": "The time  that the last barrier alignment took to complete, or how long the current alignment has taken so far (in nanoseconds). This is the time between receiving first and the last checkpoint barrier. You can find more information in the [Monitoring State and Checkpoints section](//ci.apache.org/projects/flink/flink-docs-release-1.12/ops/state/large_state_tuning.html#monitoring-state-and-checkpoints)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_checkpointAlignmentTime{task_name=\"Xform Voice Interactions\",job=\"$job\"}) by(subtask_index)",
     "legendFormat": "subtask {{subtask_index}}"
    }
   ]
  },
  {
   "title": "Checkpoint Start Delay",
   "type": "graph",
   "description": "The time  that elapsed between the creation of the last checkpoint and the time when the checkpointing process has started by this Task. This delay shows how long it takes for the first checkpoint barrier to reach the task. A high value indicates back-pressure. If only a specific task has a long start delay, the most likely reason is data skew.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_checkpointStartDelayNanos{task_name=\"Xform Voice Interactions\",job=\"$job\"}) by(subtask_index)"
    }
   ]
  }
 ]
}