{
 "title": "UCS-X Attachments QoS",
 "tags": [ "__ucsx__" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "ActiveTenantName",
    "label": "Name of active tenant to be detailed",
    "query": "ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}"
   }
  ]
 },
 "panels": [
  { "title": "HTTP request rate, rps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP request rate by Pod instance, rps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance, job) (rate(ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\", restService=\"attachments-service\"}[1m]))",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "HTTP request processing average time per Pod instance, ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance, job) (rate(ucsx_http_request_duration_sum{restService=\"attachments-service\", ccName=~\"$ActiveTenantName\"}[1m]))/sum by (pod, instance, job)(rate(ucsx_http_request_duration_count{restService=\"attachments-service\", ccName=~\"$ActiveTenantName\"}[1m]))",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  { "title": "HTTP requests details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HTTP requests activity per tenant: '$ActiveTenantName', rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (url, method) (rate(ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",restService=\"attachments-service\"}[1m]))",
     "legendFormat": "{{ method }}: {{ url }}"
    }
   ]
  },
  {
   "title": "HTTP requests processing time per tenant: '$ActiveTenantName', ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (url, method) (rate(ucsx_http_request_duration_sum{ccName=~\"$ActiveTenantName\",restService=\"attachments-service\"}[1m])/rate(ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",restService=\"attachments-service\"}[1m]))",
     "legendFormat": "{{ method }}: {{ url }}"
    }
   ]
  },
  { "title": "HTTP Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Error responses per tenant: '$ActiveTenantName', responses/second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",code=~\"4.*\",restService=\"attachments-service\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",code=~\"5.*\",restService=\"attachments-service\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Storage stream write time, ms",
   "type": "graph",
   "description": "Time spent for writind data to backend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance, job) (rate(ucsx_los_duration_sum{ccName=~\"$ActiveTenantName\", operation=\"write\"}[1m]))/sum by (pod, instance, job)(rate(ucsx_los_duration_count{ ccName=~\"$ActiveTenantName\", operation=\"write\"}[1m]))",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Storage stream read time, ms",
   "type": "graph",
   "description": "Time between reading first and the last chunk of data from the storage stream",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance, job) (rate(ucsx_los_duration_sum{ccName=~\"$ActiveTenantName\", operation=\"read\"}[1m]))/sum by (pod, instance, job)(rate(ucsx_los_duration_count{ ccName=~\"$ActiveTenantName\", operation=\"read\"}[1m]))",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "PG Pool Connections total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ucsx_los_dbPool{metric=\"total\", ccName=~\"$ActiveTenantName\"}",
     "legendFormat": "{{ccName }}-{{pod }}"
    }
   ]
  },
  {
   "title": "PG Pool Connections idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ucsx_los_dbPool{metric=\"idle\", ccName=~\"$ActiveTenantName\"}",
     "legendFormat": "{{ccName }}-{{pod }}"
    }
   ]
  },
  {
   "title": "PG Pool pending requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ucsx_los_dbPool{metric=\"wait\", ccName=~\"$ActiveTenantName\"}",
     "legendFormat": "{{ccName}}-{{pod}}"
    }
   ]
  },
  {
   "title": "PG connect time, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance, job) (rate(ucsx_los_duration_sum{ccName=~\"$ActiveTenantName\", operation=\"pg_open\"}[1m]))/sum by (pod, instance, job)(rate(ucsx_los_duration_count{ ccName=~\"$ActiveTenantName\", operation=\"pg_open\"}[1m]))",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  { "title": "UCS-X dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  { "title": "List of related dashboards", "type": "dashlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 } }
 ]
}