{
 "title": "designer-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(up{namespace=\"designer\"}, service)"
   },
   {
    "name": "Pod",
    "label": "pod",
    "query": "designer-blue.*,designer-green.*,designer-.*"
   }
  ]
 },
 "panels": [
  { "title": "Designer Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Designer Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "designer_healthcheck{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Designer GWS Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "designer_gws_healthcheck{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Designer Workspace Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "designer_workspace_healthcheck{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Designer Elasticsearch Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "designer_es_healthcheck{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Designer Infrastructure Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Designer CPU Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"designer\",namespace=\"designer\", pod=~\"[[Pod]]\"}) / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{container=\"designer\",namespace=\"designer\", pod=~\"[[Pod]]\"})) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Designer Memory Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": " (sum by (pod) (container_memory_working_set_bytes{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"})) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Designer container status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(container, pod) (kube_pod_container_status_ready{container=\"designer\",namespace=\"designer\", pod=~\"[[Pod]]\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Designer Infrastructure Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Pod CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"designer\",namespace=\"designer\", pod=~\"[[Pod]]\"}) / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{container=\"designer\",namespace=\"designer\", pod=~\"[[Pod]]\"})) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " (sum by (pod) (container_memory_working_set_bytes{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"})) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restart Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"designer\", container=\"designer\", pod=~\"[[Pod]]\"}[60m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}