{
 "title": "designer-das-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "Pod",
    "label": "pod",
    "query": "designer-das.*,designer-das-green.*, designer-das-blue.*"
   }
  ]
 },
 "panels": [
  {
   "title": "DAS Application Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DAS Health",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "das_healthcheck{namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "DAS Workspace Health",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "das_workspace_healthcheck{namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "DAS PHP Health",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "das_php_healthcheck{namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "DAS Proxy Health",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "das_proxy_healthcheck{namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "DAS Infrastructure Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Designer-DAS Container status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by(container, pod) (kube_pod_container_status_ready{container=\"designer-das\",namespace=\"designer\", pod=~\"[[Pod]]\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "DESIGNER-DAS CPU Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "(sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"designer-das\",namespace=\"designer\", pod=~\"[[Pod]]\"}) / sum by(pod) (kube_pod_container_resource_limits{resource=\"cpu\",container=\"designer-das\",namespace=\"designer\", pod=~\"[[Pod]]\"})) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Designer-DAS Memory Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(sum by (pod) (container_memory_working_set_bytes{namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}) / sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"})) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "DAS FPM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "FPM: Active Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_active_processes{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FPM: Max Active Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_max_active_processes{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FPM: Idle Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_idle_processes{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FPM: Total Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_total_processes{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FPM: Max Children Reached",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_max_children_reached{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FPM:Accept Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_accepted_conn{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FPM: Listen Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_listen_queue{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FPM: Max Listen Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fpm_max_listen_queue{container=\"designer-das\",namespace=\"designer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DAS Infrastructure Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Designer-DAS CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"designer-das\",namespace=\"designer\", pod=~\"[[Pod]]\"}) / sum by(pod) (kube_pod_container_resource_limits{resource=\"cpu\",container=\"designer-das\",namespace=\"designer\", pod=~\"[[Pod]]\"})) * 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Designer-DAS Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " (sum by (pod) (container_memory_working_set_bytes{namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}) / sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"})) * 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "DAS Disk Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(100 - ((kubelet_volume_stats_available_bytes{namespace=\"designer\",persistentvolumeclaim=~\"local-workspace-designer-das-.*\"}) / (kubelet_volume_stats_capacity_bytes{namespace=\"designer\",persistentvolumeclaim=~\"local-workspace-designer-das-.*\"})) * 100)\n",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Designer-DAS Restart Frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}[60m])",
       "legendFormat": "{{pod }}:{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "DAS Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "DAS 5XX Error Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccid, req_type) (increase(das_http_requests_total{status=\"5xx\", namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\"}[5m]))",
       "legendFormat": "{{ ccid }}: {{ req_type}}"
      }
     ]
    },
    {
     "title": "DAS 4X Error Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (ccid) (increase(das_http_requests_total{status=\"4xx\", namespace=\"designer\", container=\"designer-das\", pod=~\"[[Pod]]\",  ccid != \"none\"}[5m]))",
       "legendFormat": "{{ ccid }}"
      }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(das_http_requests_total[5m]))"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(das_http_requests_total{status=~\"4.*|5.*\"}[1h])) / sum(increase(das_http_requests_total[1h]))"
      }
     ]
    },
    {
     "title": "Top 5 Tenants by Total Requests",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(das_http_requests_total) by (ccid)",
       "legendFormat": "{{ ccid }}"
      }
     ]
    },
    {
     "title": "Requests Per Second (by type)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(das_http_requests_total[1m])) by (req_type)",
       "legendFormat": "{{ req_type }}"
      }
     ]
    },
    {
     "title": "Requests Per Second (by tenant)",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(das_http_requests_total[1m])) by (ccid)",
       "legendFormat": "{{ ccid }}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(das_http_request_duration_seconds_sum{req_type != \"other\"}[1m])) by (req_type) / sum(increase(das_http_request_duration_seconds_count{req_type != \"other\"}[1m])) by (req_type)",
       "legendFormat": "{{ req_type }}"
      }
     ]
    }
   ]
  }
 ]
}