designer:
   designerFlowSettings:
      envs:
        {
          "applicationHost": "designer-das.designer.svc.cluster.local",
          "applicationPort": 8081,
          "consult_use_app_dlg_start_done": true,
          "contactCenterForCallRecording": "RecordingServer",
          "daysToKeepBackups": 1,
          "deployURL": "/workspaces",
          "disableCCIDAuth": false,
          "disableCSRF": true,
          "disablePBAC": false,
          "disableRBAC": false,
          "disableSDRBlockList": false,
          "disableSSO": false,
          "disable_dialog_requestid_check": false,
          "docsMicroserviceURL": "https://docs.genesys.com/Documentation/PSAAS/Public/Administrator/Designer",
          "docsURL": "http://docs.genesys.com/Special:HelpLink/DESHelp?context=Draft.Welcome",
          "enableAnalytics": true,
          "enableESAuditLogs": true,
          "enableFSAuditLogs": true,
          "esMaxQueryDuration": 90,
          "esPort": 9200,
          "esServer": "elastic-es-http.infra.svc.cluster.local",
          "esUrl": "http://elastic-es-http.infra.svc.cluster.local:9200",
          "features":
            {
              "advancedScriptingInAssign": true,
              "audioConversion": false,
              "callback": false,
              "callbackrecord": false,
              "callbackv2": true,
              "campaignGroupRouting": false,
              "chatbot": false,
              "clearDTMFBuffer": false,
              "devanalytics": true,
              "digital": true,
              "enableImplicitModuleMilestones": false,
              "globalCommand": true,
              "globalCommandRespectBargein": true,
              "grammarValidation": false,
              "icm": false,
              "nexus": false,
              "personalization": false,
              "plugins": false,
              "predictiveRouting": false,
              "reportingModuleSDRInChunk": false,
              "saml": false,
              "store": false,
              "survey": true,
              "voicemail": true,
              "vxmlapp": false,
            },
          "fetchCustomerProfileTimeout": 1,
          "ffmpegPath": "/designer/ffmpeg",
          "gwsauthurl": "http://gauth-auth.gauth.svc.cluster.local:80",
          "gwsenvurl": "http://gauth-environment.gauth.svc.cluster.local:80",
          "htccKeepAliveInterval": 5,
          "htccport": 80,
          "htccprotocol": "http",
          "htccserver": "gws-service-proxy.gws.svc.cluster.local",
          "httpProxy": "",
          "idleTimeout": 840,
          "localmode":
            {
              "comment": "defaults here will point to the sample tenant and its workspace in designer postgres db ",
              "tenantId": "c0000000-1111-2222-3333-444444444444",
              "workspaceId": "workspace",
            },
          "lockdownMode": false,
          "lockdownPermissions":
            {
              "ACCOUNTS-GENERAL": "READ",
              "APP-CLONING": "NONE",
              "APP-EXPORT": "READ",
              "APP-GENERAL": "READ",
              "APP-IMPORT": "NONE",
              "APP-TAGGING": "NONE",
              "AUDIO-GENERAL": "READ_AND_UPDATE_AND_CREATE",
              "BUSINESS-GENERAL": "READ_AND_UPDATE_AND_CREATE",
              "FLOW-DIAGRAM": "READ",
              "FLOW-PROPERTY": "READ",
              "GRAMMARS-GENERAL": "READ_AND_UPDATE_AND_CREATE",
              "MESSAGES-GENERAL": "READ_AND_UPDATE_AND_CREATE",
              "WORKSPACE-SETTINGS": "READ",
            },
          "logging":
            {
              "audit": { "level": "debug" },
              "auditdebug": { "level": "debug" },
              "cli": { "level": "debug" },
              "designer": { "level": "debug" },
            },
          "maxAppSizeCompare": 1000000,
          "maxBuilds": 20,
          "maxFlowEntryCount": 20,
          "multitenancy": { "basePath": "./workspace" },
          "numBackupsToKeep": 20,
          "numChildProcesses": 2,
          "port": 8888,
          "primarySwitch": "SIP_Switch",
          "profileContextservicesPassword": "",
          "profileContextservicesURL": "",
          "profileContextservicesUser": "",
          "rbacSection": "CfgGenesysAdministratorServer",
          "recordingType": "GIR",
          "redundantHttpProxy": "",
          "rootsSRL": "",
          "s3Region": "",
          "saml": "",
          "sdrMaxObjCount": -1,
          "sdrS3BucketName": "example.${DOMAIN}.sdr",
          "sdrToS3": false,
          "ssoLoginUrl": "https://gauth.${DOMAIN}",
          "storeurl": "http://localhost:3600",
          "tenant_dbid": "1",
          "tenantid": "1",
          "urs_routing": true,
          "useUserRecordedSystemAudio": false,
          "use_ors_treatments": true,
          "usehtcc": true,
          "vxml_reporting_timeout": 30
        }
